package uk.ac.cam.ceb.como.compchem.ontology.query;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.ontology.OntModelSpec;
import org.apache.jena.query.Query;
import org.apache.jena.query.QueryExecution;
import org.apache.jena.query.QueryExecutionFactory;
import org.apache.jena.query.QueryFactory;

import org.apache.jena.query.ResultSet;
import org.apache.jena.query.ResultSetFormatter;

import org.apache.jena.rdf.model.ModelFactory;

import org.apache.jena.util.FileManager;
import org.apache.log4j.Logger;

import uk.ac.cam.ceb.como.jaxb.parsing.utils.FileUtility;
import uk.ac.cam.ceb.como.jaxb.parsing.utils.Utility;


/**
 * 
 * The Class CompChemQuery.
 *
 * @author nk510
 * 
 *  <p>This code runs sparql queries on RDF files generated by using XSLT transformations. RDF
 *         files are Abox of Compchem ontology, and stored in one 
 *         folder (for example: 'compchem_ontology'). To query these ontology files, we use Jena api. Java code searches all sparql
 *         queries saved in folder (for example: 'sparql_query'), runs it and results of these
 *         queries are saved in a target sparql results folder (for example: 'sparql_results') by using json format.</p> 
 *         
 */

public class CompChemQuery {
	
	/** The Constant TBOX_SOURCE. */
	public static final String TBOX_SOURCE = "./src/test/resources/ontology/compchem_ontology/compchem.rdf";
	public static final String ABOX_SOURCE="./src/test/resources/ontology/compchem_abox/";
	public static final String TRAGET_FOLDER="./src/test/resources/ontology/sparql_results/";
	public static final String SPARQL_FOLDER ="./src/test/resources/ontology/sparql_query/";
	
	final static Logger logger = Logger.getLogger(CompChemQuery.class.getName());
	
	/**
	 * The main method.
	 *
	 * @param args the arguments
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	
	public static void main(String[] args) throws IOException {
		
		Utility utility = new FileUtility();
		
		long startT = System.nanoTime();
		
		/**
		 * Gets the file list.
		 *
		 * @author nk510
		 * @param folderPath the folder path
		 * @return <p>Method reads all sparql files in given folder path. Supported
		 *         file extension is '.sparql'.</p>
		 */

		File[] sparqlFileList = utility.getFileList(SPARQL_FOLDER,".sparql"); 
		
		/**
		 * 
		 * Gets the ontology file list.
		 *
		 * @author nk510
		 * @param folderPath the folder path
		 * @return <p>Method reads all files in given folder path. Supported file
		 *         extensions are '.owl', '.rdf', '.ttl'. </p>
		 *         
		 */
		
		File[] aboxFileList = utility.getFileList(ABOX_SOURCE,".owl",".rdf",".ttl");

		for (File aboxFile : aboxFileList) {
			
			for(File sparqlFile: sparqlFileList) {
				
			OntModel model = getOntModel(TBOX_SOURCE, aboxFile.getAbsolutePath());
			
			String q = FileUtils.readFileToString(sparqlFile);
			
			performQuery(model, q, aboxFile.getName(), TRAGET_FOLDER);
			
			}
		}
		
		long endT = System.nanoTime();
		
		System.out.println("time: " + (endT-startT)/1000000000 + " sec.");
		
	}
	
	/**
	 * Gets the ont model.
	 *
	 * @param tboxSource the Compchemchem ontology (tbox source)
	 * @param aboxSource the ontochem data assertions (abox source)
	 * @return model Gets instance of OntModel.
	 * 
	 */

	public static OntModel getOntModel(String tboxSource, String aboxSource) {

		OntModel model = ModelFactory.createOntologyModel(OntModelSpec.OWL_DL_MEM_TRANS_INF);

		FileManager.get().readModel(model, aboxSource);
		FileManager.get().readModel(model, tboxSource);

		return model;

	}

	/**
	 * Gets the ont model.
	 *
	 * @param aboxSource the ontochem data assertions (abox source)
	 * @return model Gets instance of OntModel.
	 * 
	 */

	public static OntModel getOntModel(String aboxSource) {

		OntModel model = ModelFactory.createOntologyModel(OntModelSpec.OWL_DL_MEM_TRANS_INF);

		FileManager.get().readModel(model, aboxSource);
		
		return model;

	}
	
	/**
	 * 
	 * Perform query.
	 *
	 * @param model the instance of OntModel.
	 * @param queryString the query string.
	 * @param fileName the file name.
	 * @param targetFolder is destination folder where query result is saved.
	 * @throws IOException Signals that an I/O exception has occurred.
	 * 
	 */	

	public static void performQuery(OntModel model, String queryString, String fileName, String targetFolder) throws IOException {
		
		Query query = QueryFactory.create(queryString);

		QueryExecution qexec = QueryExecutionFactory.create(query, model);
		
		FileOutputStream fileOutputStream = null;
		
		try {

			ResultSet resultSet = qexec.execSelect();
			
			while(resultSet.hasNext()) { 
				
			/**
			 * Creates json file based on name of created OWL file including log/g09/g16 extension.
			 */
			logger.info("fileName.substring(0, fileName.lastIndexOf(\".\")): " + fileName.substring(0, fileName.lastIndexOf(".")));
			fileOutputStream=new FileOutputStream(new File(targetFolder+ fileName.substring(0, fileName.lastIndexOf("."))  +"q.json"),false);
	       		
			ResultSetFormatter.outputAsJSON(fileOutputStream, resultSet);

			}

		} finally {
			
			qexec.close();
			
			fileOutputStream.close();
		}
	}
	
}