PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix om:  <http://www.ontology-of-units-of-measure.org/resource/om-2/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

prefix ts: <https://www.theworldavatar.com/kg/ontotimeseries/>
prefix ontobms: <https://www.theworldavatar.com/kg/ontobms/>
prefix saref: <https://saref.etsi.org/core/>
prefix ontodevice: <https://www.theworldavatar.com/kg/ontodevice/>
prefix ontolab:<https://www.theworldavatar.com/kg/ontolab/>
prefix ontocape_cps_behavior: <http://www.theworldavatar.com/ontology/ontocape/chemical_process_system/CPS_behavior/behavior.owl#>
prefix ontocape_material: <http://www.theworldavatar.com/ontology/ontocape/material/material.owl#>
prefix ontocape_system: <http://www.theworldavatar.com/ontology/ontocape/upper_level/system.owl#>
prefix ontocape_phase_system:<http://www.theworldavatar.com/ontology/ontocape/material/phase_system/phase_system.owl#>
prefix : <https://www.theworldavatar.com/kg/ontobms/>

SELECT ?Property ?Value ?Unit
WHERE {
    BIND ("Name" AS ?Property ).
    BIND (123 AS ?Value).
    BIND ("Unit" AS ?Unit).
}