package com.cmclinnovations.agent.model.type;

public enum LifecycleEventType {
  APPROVED,
  SERVICE_EXECUTION,
  SERVICE_CANCELLATION,
  SERVICE_MISS_REPORT,
  ARCHIVE_COMPLETION,
  ARCHIVE_TERMINATION,
  ARCHIVE_RESCINDMENT,
}