PREFIX obe:       <https://www.theworldavatar.com/kg/ontobuiltenv/>
PREFIX rdf:       <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX geo:       <http://www.opengis.net/ont/geosparql#>
PREFIX geof:      <http://www.opengis.net/def/function/geosparql/>
PREFIX uom:       <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX ukpn:      <http://theworldavatar.com/ontology/ontocredo/ontoukpn.owl#>

SELECT DISTINCT ?poi_iri ?poi_type ?geometry
WHERE {
  ?sub a ukpn:PrimarySubStation ;
       geo:hasDefaultGeometry/geo:asWKT ?geometry

  BIND(?sub AS ?poi_iri)
  BIND(ukpn:PrimarySubStation AS ?poi_type)
}
LIMIT 10
