PREFIX obe: <https://www.theworldavatar.com/kg/ontobuiltenv/>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?building_iri ?usage
WHERE {
	{
		# Inner query to retrieve relevant usage IRI from Ontop
		SERVICE <http://pirmasens-ontop:8080/sparql/> {
        SELECT DISTINCT ?building_iri ?usage
        WHERE {
        ?building_iri obe:hasPropertyUsage ?usage.
        #Insert wanted amenities 
        VALUES ?usageType { obe:Hospital obe:Pharmacy obe:Clinic obe:School obe:Bank obe:PoliceStation obe:EatingEstablishment}
        ?usage a ?usageType.
        }
    }
}}