# MAKEFILE
# debugging: gdb episode.exe, then 'run' and 'bt'

#F77 = g77
#F90 = g95
F90 = gfortran

#flags for debugging (use for the test examples)
#F90FLAGS =  -ggdb -u -C -cpp -pedantic -ffpe-trap=invalid,underflow,zero -ftrapv -fbounds-check -finit-real=nan -#fbacktrace -fimplicit-none -finit-integer=n -ffree-form
#normal flags
#F90FLAGS =  -g -u -C -cpp -ffree-form
#normal flags
#F90FLAGS = -O3 -C -fall-intrinsics -fbounds-check
#-Wall
#F90FLAGS = -g -Wall -i8 -r8 -d8
# linux 32-bit: F90FLAGS =  -O1 -g -u -C -cpp -Wall -m32

F90FLAGS = -O3 -C -fall-intrinsics -fbounds-check


#subdirs
SRC    = ./aermap/

RUNDIR = ./bin/

TARGET = $(RUNDIR)aermap.exe

SRC_OBJ =		$(SRC)mod_main1.o         \
			$(SRC)mod_tifftags.o      \
			$(SRC)aermap.o            \
			$(SRC)sub_calchc.o        \
			$(SRC)sub_chkadj.o        \
			$(SRC)sub_chkext.o        \
			$(SRC)sub_demchk.o        \
			$(SRC)sub_nedchk.o        \
			$(SRC)sub_cnrcnv.o        \
			$(SRC)sub_demrec.o        \
			$(SRC)sub_demsrc.o        \
			$(SRC)sub_domcnv.o        \
			$(SRC)sub_initer_dem.o    \
			$(SRC)sub_initer_ned.o    \
			$(SRC)sub_nadcon.o        \
			$(SRC)sub_reccnv.o        \
			$(SRC)sub_recelv.o        \
			$(SRC)sub_srccnv.o        \
			$(SRC)sub_srcelv.o        \
			$(SRC)sub_utmgeo.o        \
			$(SRC)sub_read_tifftags.o

$(TARGET) : $(SRC_OBJ)
	$(F90) $(FFLAGS) $(SRC_OBJ) -o $@

#IMPLICIT ROULE FOR FORTRAN FILES
#.f.o:         
#                $(F90) $(F90FLAGS) -c $< -o $@
#
#.f90.o:
#	$(F90) $(F90FLAGS) -c $< -o $@

.SUFFIXES: .f .o

.f.o:
	$(F90) $(F90FLAGS) -c $< -o $@

.SUFFIXES: .F90 .o

.F90.o:
	$(F90) -c $(F90FLAGS) $*.F90

# Explicit rules and targets

clean:
	rm -f $(TARGET) core a.out

cleanall:
	rm -f $(TARGET) core a.out
	rm -f *.o *.mod
	rm -f $(SRC)*.o $(SRC)*.for~

