PREFIX bld: <http://biglinkeddata.com/>
PREFIX bl: <https://w3id.org/biolink/vocab/>
PREFIX bot: <https://w3id.org/bot#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <https://www.theworldavatar.com/kg/>
PREFIX sea: <https://www.theworldavatar.com/kg/ontosealevel/>
PREFIX be: <https://www.theworldavatar.com/kg/ontobuiltenv/>
PREFIX ic: <http://ontology.eil.utoronto.ca/icontact.owl#>
PREFIX sch: <https://schema.org/>
PREFIX dbo: <https://dbpedia.org/ontology/>
PREFIX ontoplot: <https://www.theworldavatar.com/kg/landplot/>
PREFIX plot: <https://www.theworldavatar.com/kg/ontoplot/>
PREFIX bldg: <http://www.opengis.net/citygml/building/2.0/>

SELECT *
WHERE {
  	?building sea:hasPotentialImpact ?s.
  	?s a bldg:Building.
  	?s bldg:lod0FootPrint ?g.
}
LIMIT 5
