package uk.ac.cam.cares.jps.agent.dashboard.json.panel.types;

import uk.ac.cam.cares.jps.agent.dashboard.json.panel.layout.UnitMapper;
import uk.ac.cam.cares.jps.agent.dashboard.utils.StringHelper;


import java.util.List;

/**
 * A Java representation of a JSON-like model that encapsulates and enforces information
 * about time series chart syntax specific to Grafana dashboard.
 *
 * @author qhouyee
 */
public class TimeSeriesChart extends TemplatePanel {
    private String thresholdStyle = "off";
    private String thresholdKeyValue = "";

    /**
     * Standard Constructor.
     *
     * @param measure            The measure name for this variable.
     * @param itemGroup          The item group for this measure - asset type or rooms.
     * @param unit               Optional measure unit symbol. Can be null.
     * @param databaseId         The database connection ID generated by Grafana.
     * @param timeSeriesMetadata A list of items and their metadata for the specified measure.
     * @param thresholds         An array of threshold: Position 1 - min threshold; Position 2- max threshold.
     */
    public TimeSeriesChart(String measure, String itemGroup, String unit, String databaseId, List<String[]> timeSeriesMetadata, String[] thresholds) {
        super(measure, itemGroup, databaseId, timeSeriesMetadata);
        // Sets the unit for retrieval
        super.setUnit(unit);
        // Set Title for panel
        // Title is: Measure of Item Group [Unit]
        String titleContent = StringHelper.addSpaceBetweenCapitalWords(measure) + " of " + StringHelper.addSpaceBetweenCapitalWords(itemGroup);
        titleContent = unit.equals("null") ? titleContent : titleContent + " [" + unit + "]"; // Unit is optional
        super.setTitle(titleContent);
        // Set Description for panel
        // Description should follow the measure name and item group
        String description = "A chart displaying the time series of " + measure.toLowerCase() + " for " + itemGroup.toLowerCase();
        super.setDescription(description);
        // If there are thresholds, override the following items
        if (thresholds.length != 0) {
            this.thresholdStyle = "area";
            this.thresholdKeyValue = "\"thresholds\":{\"mode\": \"absolute\", \"steps\": [" +
                    "{\"color\":\"red\",\"value\":null},{\"color\":\"green\",\"value\":" + thresholds[0] + "}," +
                    "{\"color\":\"red\",\"value\":" + thresholds[1] + "}]},";
        }
    }

    /**
     * Construct the Time Series Chart syntax as a String.
     *
     * @param height    Height of the panel.
     * @param width     Width of the panel.
     * @param xPosition X position within the dashboard.
     * @param yPosition Y position within the dashboard.
     * @return The Time Series Chart syntax as a String.
     */
    @Override
    public String construct(int height, int width, int xPosition, int yPosition) {
        StringBuilder builder = new StringBuilder();
        builder.append("{").append(super.genCommonJson(height, width, xPosition, yPosition))
                // Chart type must be set to time series
                .append(",\"type\": \"timeseries\",")
                // Field Configuration
                .append("\"fieldConfig\": { ")
                // Default field configuration
                .append("\"defaults\": {\"color\": {\"mode\": \"palette-classic\"},")
                // Custom parts of field configurations
                .append("\"custom\":{").append("\"axisCenteredZero\":false,\"axisColorMode\":\"text\",")
                .append("\"axisLabel\":\"\",\"axisPlacement\":\"auto\", \"barAlignment\":0, \"drawStyle\":\"line\",")
                .append("\"fillOpacity\":0,\"gradientMode\":\"none\",")
                .append("\"hideFrom\":{\"legend\":false, \"tooltip\":false, \"viz\":false},")
                .append("\"lineInterpolation\":\"linear\", \"lineWidth\":1, \"pointSize\":5,")
                .append("\"scaleDistribution\":{\"type\":\"linear\"}, \"showPoints\":\"auto\", \"spanNulls\":false,")
                .append("\"stacking\":{\"group\":\"A\", \"mode\":\"none\"}, \"thresholdsStyle\":{\"mode\":\"" + this.thresholdStyle + "\"}")
                .append("},") // End of custom parts
                .append(this.thresholdKeyValue)
                .append("\"mappings\": [],")
                .append("\"unit\":\"").append(UnitMapper.getUnitSyntax(super.getUnit())).append("\"")
                .append("},") // End of defaults
                .append("\"overrides\": []")
                .append("},") // End of field configuration
                // Options
                .append("\"options\":{")
                // Legend options
                .append("\"legend\":{\"calcs\": [], \"displayMode\":\"list\",\"placement\":\"bottom\",\"showLegend\":true},")
                // Tooltip options
                .append("\"tooltip\":{\"mode\":\"single\",\"sort\":\"none\"}")
                .append("}") // end of options
                .append("}");
        return builder.toString();
    }
}
