PREFIX j1:<http://www.theworldavatar.com/ontology/ontopowsys/PowSysRealization.owl#>
PREFIX powsys: <http://www.theworldavatar.com/ontology/ontopowsys/OntoPowSys.owl#>
PREFIX powbehave: <http://www.theworldavatar.com/ontology/ontopowsys/PowSysBehavior.owl#>
PREFIX env: <http://www.theworldavatar.com/ontology/ontobuiltenv/OntoBuiltEnv.owl>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX ts: <https://www.theworldavatar.com/kg/ontotimeseries/>

SELECT ?Measurement ?Name ?Unit
WHERE {
  [IRI] powsys:hasBusNode ?busnode.
  ?busnode powbehave:hasActivePowerAbsorbed ?activePower.
  ?activePower om:hasValue ?Measurement.
  BIND("Absorbed Active Power" AS ?Name).
  BIND("kilowatt" AS ?Unit)
}