"""IRIS"""

RDF = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
OWL = "http://www.w3.org/2002/07/owl#"
RDFS = "http://www.w3.org/2000/01/rdf-schema#"
XSD = "http://www.w3.org/2001/XMLSchema#"

RDF_TYPE =  RDF + 'type'
OWL_SAMEAS = OWL + "sameAs"
XSD_DATETIME = XSD + "dateTime"
RDFS_LABEL = RDFS + "label"

"""OntoCAPE"""
ONTOCAPE_UPPER_LEVEL_SYSTEM = "http://www.theworldavatar.com/ontology/ontocape/upper_level/system.owl#"    
ONTOCAPE_DERIVED_SI_UNITS =  "http://www.theworldavatar.com/ontology/ontocape/supporting_concepts/SI_unit/derived_SI_units.owl#"
ONTOECAPE_SPACE_AND_TIME_EXTENDED = "http://www.theworldavatar.com/ontology/ontocape/supporting_concepts/space_and_time/space_and_time_extended.owl#"
ONTOECAPE_SPACE_AND_TIME = "http://www.theworldavatar.com/ontology/ontocape/supporting_concepts/space_and_time/space_and_time.owl#"
ONTOECAPE_TECHNICAL_SYSTEM = "http://www.theworldavatar.com/ontology/ontocape/upper_level/technical_system.owl#"
ONTOCAPE_NETWORK_SYSTEM = "http://www.theworldavatar.com/ontology/ontocape/upper_level/network_system.owl#"
ONTOCAPE_MATHEMATICAL_MODEL = "http://www.theworldavatar.com/ontology/ontocape/model/mathematical_model.owl#"
ONTOCAPE_PHYSICAL_DIMENSION = "http://www.theworldavatar.com/ontology/ontocape/supporting_concepts/physical_dimension/physical_dimension.owl#"
ONTOCAPE_COORDINATE_SYSTEM = "http://www.theworldavatar.com/ontology/ontocape/upper_level/coordinate_system.owl#"
ONTOCAPE_SI_UNITS = "http://www.theworldavatar.com/ontology/ontocape/supporting_concepts/SI_unit/SI_unit.owl#"
ONTOCAPE_MATHEMATICAL_RELATION = "http://www.theworldavatar.com/ontology/ontocape/supporting_concepts/mathematical_relation/mathematical_relation.owl#"
ONTOCAPE_GEOMETRY = "http://www.theworldavatar.com/ontology/ontocape/supporting_concepts/geometry/geometry.owl#"

META_MEDOL_TOPOLOGY = "http://www.theworldavatar.com/ontology/meta_model/topology/topology.owl#"

ONTOCAPE_UPPER_LEVEL_SYSTEM_ISCOMPOSEDOFSUBSYSTEM = ONTOCAPE_UPPER_LEVEL_SYSTEM + "isComposedOfSubsystem"
META_MEDOL_TOPOLOGY_HASOUTPUT = META_MEDOL_TOPOLOGY + "hasOutput"
ONTOECAPE_TECHNICAL_SYSTEM_HASREALIZATIONASPECT = ONTOECAPE_TECHNICAL_SYSTEM + "hasRealizationAspect"
ONTOECAPE_TECHNICAL_SYSTEM_HASREQUIREMENTSASPECT = ONTOECAPE_TECHNICAL_SYSTEM + "hasRequirementsAspect"
ONTOECAPE_TECHNICAL_SYSTEM_REALIZES = ONTOECAPE_TECHNICAL_SYSTEM + "realizes"
ONTOCAPE_UPPER_LEVEL_SYSTEM_HASVALUE = ONTOCAPE_UPPER_LEVEL_SYSTEM + "hasValue"
ONTOCAPE_UPPER_LEVEL_SYSTEM_NUMERICALVALUE = ONTOCAPE_UPPER_LEVEL_SYSTEM + "numericalValue"
ONTOCAPE_UPPER_LEVEL_SYSTEM_CONTAINS = ONTOCAPE_UPPER_LEVEL_SYSTEM + "contains"
ONTOCAPE_DERIVED_SI_UNITS_HASTIMEPERIOD = ONTOCAPE_DERIVED_SI_UNITS + "hasTimePeriod"
ONTOECAPE_SPACE_AND_TIME_HASSTARTINGTIME = ONTOECAPE_SPACE_AND_TIME + "hasStartingTime"
ONTOCAPE_COORDINATE_SYSTEM_COORDINATEVALUE = ONTOCAPE_COORDINATE_SYSTEM + "CoordinateValue"
ONTOCAPE_UPPER_LEVEL_SYSTEM_ISDIRECTSUBSYSTEMOF = ONTOCAPE_UPPER_LEVEL_SYSTEM + "isDirectSubsystemOf"
ONTOCAPE_NETWORK_SYSTEM_LEAVES = ONTOCAPE_NETWORK_SYSTEM + "leaves"
ONTOCAPE_NETWORK_SYSTEM_ENTERS = ONTOCAPE_NETWORK_SYSTEM + "enters"
ONTOCAPE_GEOMETRY_HASSHAPEREPRESENTATION = ONTOCAPE_GEOMETRY + "hasShapeRepresentation"
ONTOCAPE_GEOMETRY_HAS_LENGTH = ONTOCAPE_GEOMETRY + "has_length"
    
"""OntoEIP"""
ONTOEIP_SYSTEM_REALIZATION = "http://www.theworldavatar.com/ontology/ontoeip/system_aspects/system_realization.owl#"
ONTOEIP_SYSTEM_FUNCTION = "http://www.theworldavatar.com/ontology/ontoeip/system_aspects/system_function.owl#"
ONTOEIP_POWERPLANT = "http://www.theworldavatar.com/ontology/ontoeip/powerplants/PowerPlant.owl#"
ONTOEIP_UPPER_LEVEL_SYSTEM_V1 = "http://www.theworldavatar.com/ontology/ontoeip/upper_level/system_v1.owl#"
ONTOEIP_SYSTEM_PERFORMANCE = "http://www.theworldavatar.com/ontology/ontoeip/system_aspects/system_performance.owl#"
ONTOEIP_SYSTEM_REQUIREMENT = "http://www.theworldavatar.com/ontology/ontoeip/system_aspects/system_requirement.owl#" # Undefined 
ONTOPOWSYS = "http://www.theworldavatar.com/ontology/ontopowsys/OntoPowSys.owl#"

ONTOEIP_SYSTEM_REQUIREMENT_DESIGNCAPACITY = ONTOEIP_SYSTEM_REQUIREMENT + "DesignCapacity"
ONTOEIP_POWERPLANT_POWERPLANT = ONTOEIP_POWERPLANT + "PowerPlant"
ONTOEIP_POWERPLANT_CONSUMESPRIMARYFUEL = ONTOEIP_POWERPLANT + "consumesPrimaryFuel"
ONTOEIP_POWERPLANT_USESGENERATIONTECHNOLOGY = ONTOEIP_POWERPLANT + "usesGenerationTechnology"
ONTOEIP_POWERPLANT_HASEMISSIONFACTOR = ONTOEIP_POWERPLANT + "hasEmissionFactor"
ONTOEIP_POWERPLANT_DESIGNCAPACITY = ONTOEIP_POWERPLANT + "DesignCapacity"
ONTOEIP_POWERPLANT_POWERGENERATOR = ONTOEIP_POWERPLANT + "PowerGenerator" 

"""OntoPowSys"""
ONTOPOWSYS_POWSYSREALIZATION = "http://www.theworldavatar.com/ontology/ontopowsys/PowSysRealization.owl#"
ONTOPOWSYS_POWSYSFUNCTION = "http://www.theworldavatar.com/ontology/ontopowsys/PowSysFunction.owl#"
ONTOPOWSYS_POWERSYSTEMMODEL = "http://www.theworldavatar.com/ontology/ontopowsys/model/PowerSystemModel.owl#"
ONTOPOWSYS_POWSYSPERFORMANCE = "http://www.theworldavatar.com/ontology/ontopowsys/PowSysPerformance.owl#"
ONTOPOWSYS_ONTOPOWSYS = "http://www.theworldavatar.com/ontology/ontopowsys/OntoPowSys.owl#"

ONTOPOWSYS_POWSYSREALIZATION_BUSNODE = ONTOPOWSYS_POWSYSREALIZATION + "BusNode"
ONTOPOWSYS_POWSYSREALIZATION_POWERGENERATOR = ONTOPOWSYS_POWSYSREALIZATION + "PowerGenerator"
ONTOPOWSYS_POWSYSPERFORMANCE_HASFIXEDMAINTENANCECOST = ONTOPOWSYS_POWSYSPERFORMANCE + "hasFixedMaintenanceCost"
ONTOPOWSYS_POWSYSPERFORMANCE_HASCOST = ONTOPOWSYS_POWSYSPERFORMANCE + "hasCost"
ONTOPOWSYS_POWSYSPERFORMANCE_HASFUELCOST = ONTOPOWSYS_POWSYSPERFORMANCE + "hasFuelCost"
ONTOPOWSYS_POWSYSREALIZATION_ELECTRICALLINE = ONTOPOWSYS_POWSYSREALIZATION + "ElectricalLine"
ONTOPOWSYS_POWSYSREALIZATION_OVERHEADLINE = ONTOPOWSYS_POWSYSREALIZATION + "OverheadLine"
ONTOPOWSYS_POWSYSREALIZATION_HASVOLTAGELEVEL = ONTOPOWSYS_POWSYSREALIZATION + "hasVoltageLevel"
ONTOPOWSYS_POWSYSREALIZATION_HASNUMBEROFPARALLELLINE = ONTOPOWSYS_POWSYSREALIZATION + "hasNumberOfParallelLine"

"""OntoSDG"""
ONTOSDG = "http://theworldavatar.com/ontology/ontosdg/OntoSDG.owl#"

"""OntoSpecies"""
ONTOSPECIES = "http://www.theworldavatar.com/ontology/ontospecies/OntoSpecies.owl#"

"""Bibtex"""
BIBTEX = "https://zeitkunst.org/bibtex/0.2/bibtex.owl#"

"""OntoEnergySystem"""
ONTOENERGYSYSTEM = "http://www.theworldavatar.com/ontology/ontoenergysystem/OntoEnergySystem.owl#"

ONTOENERGYSYSTEM_HASWGS84LATITUDELONGITUDE = ONTOENERGYSYSTEM + "hasWGS84LatitudeLongitude"
ONTOENERGYSYSTEM_HASRELEVANTPLACE = ONTOENERGYSYSTEM + "hasRelevantPlace"
ONTOENERGYSYSTEM_ELECTRICPOWERSYSTEM = ONTOENERGYSYSTEM + "ElectricPowerSystem"
ONTOENERGYSYSTEM_ADMINISTRATIVEDIVISION = ONTOENERGYSYSTEM + "AdministrativeDivision"
ONTOENERGYSYSTEM_HASLOCALAUTHORITYCODE = ONTOENERGYSYSTEM + "hasLocalAuthorityCode"
ONTOENERGYSYSTEM_ISOBSERVEDIN = ONTOENERGYSYSTEM + "isObservedIn"
ONTOENERGYSYSTEM_ISTOPOLOGYOF = ONTOENERGYSYSTEM + "isTopologyOf"
ONTOENERGYSYSTEM_POWERGRIDTOPOLOGY = ONTOENERGYSYSTEM + "PowerGridTopology"

"""GB"""
GB = "https://dbpedia.org/page/Great_Britain"

"""ONS"""
ONS = "http://statistics.data.gov.uk/def/statistical-geography#"
ONS_ENTITY = "http://statistics.data.gov.uk/def/statistical-entity#"
ONS_GEOSPARQL = "http://www.opengis.net/ont/geosparql#"

ONS_STATISTICAL_GEOGRAPHY = ONS + "Statistical-Geography"
ONS_ENTITY_CODE = ONS_ENTITY + "code"
ONS_GEOSPARQL_HASGEOMETRY = ONS_GEOSPARQL + "hasGeometry"
ONS_GEOSPARQL_ASWKT = ONS_GEOSPARQL + "asWKT"

FOI = "http://publishmydata.com/def/ontology/foi/"
FOI_WITHIN = FOI + "within"
FOI_CODE = FOI + "code"