package uk.ac.cam.ceb.como.paper.enthalpy.io;

import java.io.File;
import java.util.Map;

import uk.ac.cam.ceb.como.enthalpy.estimation.balanced_reaction.solver.LPSolver;
import uk.ac.cam.ceb.como.enthalpy.estimation.balanced_reaction.solver.SolverHelper;
import uk.ac.cam.ceb.como.enthalpy.estimation.balanced_reaction.solver.glpk.TerminalGLPKSolver;

/**
 * 
 *  @author mk510 (caresssd@hermes.cam.ac.uk)
 *  @author am2145( am2145@cam.ac.uk )
 *
 */

public class LoadSolver {

	/**
	 * 
	 * @param mapElPairing the hash map that remembers species name and number of electrons for that species. 
	 * @param timeout time to terminate
	 * @param destinationFolder the folder where output files are stored that are generated by the LP solver.
	 * @return the solver object.
	 * 
	 */

	public LPSolver loadLPSolver(Map<String, Integer[]> mapElPairing, long timeout, String destinationFolder) {
		
		     SolverHelper.add(mapElPairing);

	        LPSolver solver = new TerminalGLPKSolver(timeout, false, true); //timeout=15000
	        
	        solver.setDirectory(new File(destinationFolder));
	        
	        return solver;
	}
}