{
 "title": "District Heating Generation",
 "time": { "from": "2020-01-01T00:00:00.000Z", "to": "2020-01-07T23:00:00.000Z" },
 "panels": [
  {
   "title": "Current heat sourcing [MWh]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"timecol\", \"column1\" AS \"Optimised forecast\" FROM \"<heat_sourcing>\"\r\nORDER BY time LIMIT 1;"
    }
   ]
  },
  {
   "title": "Heat sourcing [MWh]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time AS \"timecol\", \"column1\" AS \"Optimised forecast\" FROM \"<heat_sourcing>\";"
    }
   ]
  },
  {
   "title": "Current heat generation [MWh]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, SUM(\"column1\") AS \"Total\"\r\nFROM\r\n(\r\n    SELECT time,\"column1\"\r\n    FROM \"<heat_generation_GasTurbine>\"\r\n    UNION ALL\r\n    SELECT time,\"column1\"\r\n    FROM \"<heat_generation_HeatBoiler4>\"\r\n    UNION ALL\r\n    SELECT time,\"column1\"\r\n    FROM \"<heat_generation_HeatBoiler5>\"\r\n    UNION ALL\r\n    SELECT time,\"column1\"\r\n    FROM \"<heat_generation_HeatBoiler6>\"\r\n) t\r\nGROUP BY time ORDER BY time LIMIT 1;"
    }
   ]
  },
  {
   "title": "Total heat generation [MWh]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT time, SUM(\"column1\") AS \"Optimised forecast\"\r\nFROM\r\n(\r\n    SELECT time,\"column1\"\r\n    FROM \"<heat_generation_GasTurbine>\"\r\n    UNION ALL\r\n    SELECT time,\"column1\"\r\n    FROM \"<heat_generation_HeatBoiler4>\"\r\n    UNION ALL\r\n    SELECT time,\"column1\"\r\n    FROM \"<heat_generation_HeatBoiler5>\"\r\n    UNION ALL\r\n    SELECT time,\"column1\"\r\n    FROM \"<heat_generation_HeatBoiler6>\"\r\n) t\r\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Total gas consumption [MWh]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT time, SUM(\"column1\") AS \"Optimised forecast\"\r\nFROM\r\n(\r\n    SELECT time,\"column1\"\r\n    FROM \"<gas_consumption_GasTurbine>\"\r\n    UNION ALL\r\n    SELECT time,\"column1\"\r\n    FROM \"<gas_consumption_HeatBoiler4>\"\r\n    UNION ALL\r\n    SELECT time,\"column1\"\r\n    FROM \"<gas_consumption_HeatBoiler5>\"\r\n    UNION ALL\r\n    SELECT time,\"column1\"\r\n    FROM \"<gas_consumption_HeatBoiler6>\"\r\n) t\r\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Current heat generation per generator [MWh]",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time,\"column1\" AS \"Boiler 4\" FROM \"<heat_generation_HeatBoiler4>\" ORDER BY time LIMIT 1;\r\n"
    },
    {
     "rawSql": "SELECT time,\"column1\" AS \"Boiler 5\" FROM \"<heat_generation_HeatBoiler5>\" ORDER BY time LIMIT 1;\r\n"
    },
    {
     "rawSql": "SELECT time,\"column1\" AS \"Boiler 6\" FROM \"<heat_generation_HeatBoiler6>\" ORDER BY time LIMIT 1;\r\n"
    },
    {
     "rawSql": "SELECT time,\"column1\" AS \"Gas Turbine\" FROM \"<heat_generation_GasTurbine>\"  ORDER BY time LIMIT 1;"
    }
   ]
  },
  {
   "title": "Heat generation per generator [MWh]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT time,\"column1\" AS \"Gas Turbine\" FROM \"<heat_generation_GasTurbine>\""
    },
    {
     "rawSql": "SELECT time,\"column1\" AS \"Boiler 4\" FROM \"<heat_generation_HeatBoiler4>\"\r\n"
    },
    {
     "rawSql": "SELECT time,\"column1\" AS \"Boiler 5\" FROM \"<heat_generation_HeatBoiler5>\"\r\n"
    },
    {
     "rawSql": "SELECT time,\"column1\" AS \"Boiler 6\" FROM \"<heat_generation_HeatBoiler6>\""
    }
   ]
  },
  {
   "title": "Gas consumption per generator [MWh]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT time,\"column1\" AS \"Gas Turbine\" FROM \"<gas_consumption_GasTurbine>\""
    },
    {
     "rawSql": "SELECT time,\"column1\" AS \"Boiler 4\" FROM \"<gas_consumption_HeatBoiler4>\""
    },
    {
     "rawSql": "SELECT time,\"column1\" AS \"Boiler 5\" FROM \"<gas_consumption_HeatBoiler5>\""
    },
    {
     "rawSql": "SELECT time,\"column1\" AS \"Boiler 6\" FROM \"<gas_consumption_HeatBoiler6>\""
    }
   ]
  },
  {
   "title": "Electricity co-generation [MWh]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT time,\"column1\" AS \"Gas Turbine\" FROM \"<elec_cogen>\""
    }
   ]
  }
 ]
}