// Example HTTP request to update transaction record for single property

// property_iris: IRI of instantiated building to instantiate/update property sales data for
//                (trailing '<' and '>' are optional/not required)

POST http://128.199.197.40:5002/api/landregistry/update
Content-Type: application/json

{ "query": {
      "property_iris": "https://www.theworldavatar.com/kg/ontobuiltenv/Building_21367cb9-6823-4133-9204-c88b3f8850a7"
    }
}
