// Example HTTP request to scale time series data for instantiated property price index

// ppi_iri: IRI of instantiated property price index
//          (without trailing '<' and '>')
// scaler: Scaling factor by which to scale instantiated property price data
//         (0.0 ... 1.0)

POST http://165.232.172.16:5008/landregistry/scale_ppi
Content-Type: application/json

{ "query": {
      "ppi_iri": "https://www.theworldavatar.com/kg/ontobuiltenv/PropertyPriceIndex_0179cd66-c96a-4fe1-b25a-c4ce118f44eb",
      "scaler": 0.95
    }
}
