###--- Supported observation types by OntoEMS (relevant for UK Air) ---###
AIR_TEMPERATURE = 'AirTemperature'
WIND_SPEED = 'WindSpeed'
WIND_GUST = 'WindGust'
WIND_DIRECTION = 'WindDirection'
FEELS_LIKE_TEMPERATURE = 'FeelsLikeTemperature'
DEW_POINT = 'DewPoint'
ATMOSPHERIC_PRESSURE = 'AtmosphericPressure'
RELATIVE_HUMIDITY = 'RelativeHumidity'
AIR_POLLUTANT_CONCENTRATION = 'AirPollutantConcentration'
SO2_CONCENTRATION = 'SulfurDioxideConcentration'
NOX_CONCENTRATION = 'NitrogenOxidesConcentration'
NO_CONCENTRATION = 'NitrogenMonoxideConcentration'
NO2_CONCENTRATION = 'NitrogenDioxideConcentration'
PM_CONCENTRATION = 'ParticulateMatterConcentration'
PM2_5_CONCENTRATION = 'PM2.5Concentration'
PM10_CONCENTRATION = 'PM10Concentration'
O3_CONCENTRATION = 'OzoneConcentration'
