PREFIX rdf:		<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX loc:		<http://www.bigdata.com/rdf/geospatial/literals/v1#>
PREFIX ns:		<http://www.theworldavatar.com/ontology/ontogasgrid/gas_network_components.owl#>

SELECT (COUNT(*) AS ?RESULT)
WHERE
{
	?term rdf:type ns:GasTerminal.
}