DB_USER='postgres'
DB_PASSWORD='postgres'
DB_URL='jdbc:postgresql://localhost:7432/postgres'
QUERY_ENDPOINT='http://localhost:8080/blazegraph/namespace/test/sparql'
UPDATE_ENDPOINT='http://localhost:8080/blazegraph/namespace/test/sparql'
ONTOP_URL=''
