# This file shows a sample HTTP request to evaluate the (forecasting) errors between two time series

# The endpoint requires two time series data IRIs (i.e., IRIs with attached 'ts:hasTimeSeries' relationships)
# - dataIRI_target: dataIRI of the (historical) target time series
# - dataIRI_fc: dataIRI of the forecast time series

# Docker deployment:
POST http://localhost:5001/evaluate_errors
# Stack deployment (using stack-manager-input-config.json via stack-manager):
#POST http://localhost:3838/forecastingAgent/evaluate_errors
Content-Type: application/json

{ "query": {
      "dataIRI_target": "https://www.theworldavatar.com/kg/HistoricalMeasure_uuid",
      "dataIRI_fc" : "https://www.theworldavatar.com/kg/Forecast_uuid"
    }
}
