
POST http://127.0.0.1:5000/api/forecastingAgent/forecast
Content-Type: application/json

{ "query": {
      //"dataIRI": "https://www.theworldavatar.com/kg/pms_dh/HasHeatDemand_172bfe76-0c1c-4463-b03e-bae2c1f50f4d",
      "dataIRI": "https://www.theworldavatar.com/kg/pms_dh/Temperature_0d5a1129-b441-4a61-b983-dd578c52e3f5",
      "force_mapping" : "DEFAULT",
      "forecast_start_date": "2019-10-17T01:00:00Z",
      "horizon": 168
    }
}
