FROM tiangolo/uwsgi-nginx-flask:python3.8 as flask

COPY Marie/ ./Marie
COPY uwsgi.ini ./uwsgi.ini
COPY static/ ./static
COPY templates/ ./templates
COPY main.py ./main.py
COPY requirements_linux.txt ./requirements_linux.txt

RUN pip install --no-cache-dir -r requirements_linux.txt
RUN mkdir ./DATA
RUN wget http://159.223.42.53:8080/CrossGraph.zip && unzip CrossGraph.zip -d . && rm CrossGraph.zip
RUN wget http://159.223.42.53:8080/Dictionaries.zip && unzip Dictionaries.zip -d . && rm Dictionaries.zip
RUN wget http://159.223.42.53:8080/EntityLinking.zip && unzip EntityLinking.zip -d . && rm EntityLinking.zip
RUN wget http://159.223.42.53:8080/bert_pretrained.zip && unzip bert_pretrained.zip -d . && rm bert_pretrained.zip
ADD http://159.223.42.53:8080/label_dict.js ./static/js/label_dict.js
