//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 04:17:37 PM BST 
//


package uk.ac.cam.ceb.como.io.chem.file.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.cam.ceb.como.io.chem.file.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.cam.ceb.como.io.chem.file.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link ReactionStepList }
     * 
     */
    public ReactionStepList createReactionStepList() {
        return new ReactionStepList();
    }

    /**
     * Create an instance of {@link MetadataList }
     * 
     */
    public MetadataList createMetadataList() {
        return new MetadataList();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link ReactionStep }
     * 
     */
    public ReactionStep createReactionStep() {
        return new ReactionStep();
    }

    /**
     * Create an instance of {@link ReactionScheme }
     * 
     */
    public ReactionScheme createReactionScheme() {
        return new ReactionScheme();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link Reaction }
     * 
     */
    public Reaction createReaction() {
        return new Reaction();
    }

    /**
     * Create an instance of {@link ReactiveCentre }
     * 
     */
    public ReactiveCentre createReactiveCentre() {
        return new ReactiveCentre();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link AtomTypeList }
     * 
     */
    public AtomTypeList createAtomTypeList() {
        return new AtomTypeList();
    }

    /**
     * Create an instance of {@link AtomType }
     * 
     */
    public AtomType createAtomType() {
        return new AtomType();
    }

    /**
     * Create an instance of {@link Molecule }
     * 
     */
    public Molecule createMolecule() {
        return new Molecule();
    }

    /**
     * Create an instance of {@link Angle }
     * 
     */
    public Angle createAngle() {
        return new Angle();
    }

    /**
     * Create an instance of {@link Arg }
     * 
     */
    public Arg createArg() {
        return new Arg();
    }

    /**
     * Create an instance of {@link Atom }
     * 
     */
    public Atom createAtom() {
        return new Atom();
    }

    /**
     * Create an instance of {@link Array }
     * 
     */
    public Array createArray() {
        return new Array();
    }

    /**
     * Create an instance of {@link Matrix }
     * 
     */
    public Matrix createMatrix() {
        return new Matrix();
    }

    /**
     * Create an instance of {@link Scalar }
     * 
     */
    public Scalar createScalar() {
        return new Scalar();
    }

    /**
     * Create an instance of {@link AtomParity }
     * 
     */
    public AtomParity createAtomParity() {
        return new AtomParity();
    }

    /**
     * Create an instance of {@link Electron }
     * 
     */
    public Electron createElectron() {
        return new Electron();
    }

    /**
     * Create an instance of {@link Particle }
     * 
     */
    public Particle createParticle() {
        return new Particle();
    }

    /**
     * Create an instance of {@link Vector3 }
     * 
     */
    public Vector3 createVector3() {
        return new Vector3();
    }

    /**
     * Create an instance of {@link Expression }
     * 
     */
    public Expression createExpression() {
        return new Expression();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Gradient }
     * 
     */
    public Gradient createGradient() {
        return new Gradient();
    }

    /**
     * Create an instance of {@link Operator }
     * 
     */
    public Operator createOperator() {
        return new Operator();
    }

    /**
     * Create an instance of {@link AtomArray }
     * 
     */
    public AtomArray createAtomArray() {
        return new AtomArray();
    }

    /**
     * Create an instance of {@link BondArray }
     * 
     */
    public BondArray createBondArray() {
        return new BondArray();
    }

    /**
     * Create an instance of {@link Bond }
     * 
     */
    public Bond createBond() {
        return new Bond();
    }

    /**
     * Create an instance of {@link BondType }
     * 
     */
    public BondType createBondType() {
        return new BondType();
    }

    /**
     * Create an instance of {@link BondStereo }
     * 
     */
    public BondStereo createBondStereo() {
        return new BondStereo();
    }

    /**
     * Create an instance of {@link Crystal }
     * 
     */
    public Crystal createCrystal() {
        return new Crystal();
    }

    /**
     * Create an instance of {@link CellParameter }
     * 
     */
    public CellParameter createCellParameter() {
        return new CellParameter();
    }

    /**
     * Create an instance of {@link Symmetry }
     * 
     */
    public Symmetry createSymmetry() {
        return new Symmetry();
    }

    /**
     * Create an instance of {@link Transform3 }
     * 
     */
    public Transform3 createTransform3() {
        return new Transform3();
    }

    /**
     * Create an instance of {@link Formula }
     * 
     */
    public Formula createFormula() {
        return new Formula();
    }

    /**
     * Create an instance of {@link Join }
     * 
     */
    public Join createJoin() {
        return new Join();
    }

    /**
     * Create an instance of {@link Length }
     * 
     */
    public Length createLength() {
        return new Length();
    }

    /**
     * Create an instance of {@link Torsion }
     * 
     */
    public Torsion createTorsion() {
        return new Torsion();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link PropertyList }
     * 
     */
    public PropertyList createPropertyList() {
        return new PropertyList();
    }

    /**
     * Create an instance of {@link Observation }
     * 
     */
    public Observation createObservation() {
        return new Observation();
    }

    /**
     * Create an instance of {@link ZMatrix }
     * 
     */
    public ZMatrix createZMatrix() {
        return new ZMatrix();
    }

    /**
     * Create an instance of {@link BondTypeList }
     * 
     */
    public BondTypeList createBondTypeList() {
        return new BondTypeList();
    }

    /**
     * Create an instance of {@link AtomSet }
     * 
     */
    public AtomSet createAtomSet() {
        return new AtomSet();
    }

    /**
     * Create an instance of {@link BondSet }
     * 
     */
    public BondSet createBondSet() {
        return new BondSet();
    }

    /**
     * Create an instance of {@link Mechanism }
     * 
     */
    public Mechanism createMechanism() {
        return new Mechanism();
    }

    /**
     * Create an instance of {@link MechanismComponent }
     * 
     */
    public MechanismComponent createMechanismComponent() {
        return new MechanismComponent();
    }

    /**
     * Create an instance of {@link ReactantList }
     * 
     */
    public ReactantList createReactantList() {
        return new ReactantList();
    }

    /**
     * Create an instance of {@link Reactant }
     * 
     */
    public Reactant createReactant() {
        return new Reactant();
    }

    /**
     * Create an instance of {@link Substance }
     * 
     */
    public Substance createSubstance() {
        return new Substance();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link SubstanceList }
     * 
     */
    public SubstanceList createSubstanceList() {
        return new SubstanceList();
    }

    /**
     * Create an instance of {@link SpectatorList }
     * 
     */
    public SpectatorList createSpectatorList() {
        return new SpectatorList();
    }

    /**
     * Create an instance of {@link Spectator }
     * 
     */
    public Spectator createSpectator() {
        return new Spectator();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link ConditionList }
     * 
     */
    public ConditionList createConditionList() {
        return new ConditionList();
    }

    /**
     * Create an instance of {@link TransitionState }
     * 
     */
    public TransitionState createTransitionState() {
        return new TransitionState();
    }

    /**
     * Create an instance of {@link ProductList }
     * 
     */
    public ProductList createProductList() {
        return new ProductList();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link Band }
     * 
     */
    public Band createBand() {
        return new Band();
    }

    /**
     * Create an instance of {@link TableCell }
     * 
     */
    public TableCell createTableCell() {
        return new TableCell();
    }

    /**
     * Create an instance of {@link TableContent }
     * 
     */
    public TableContent createTableContent() {
        return new TableContent();
    }

    /**
     * Create an instance of {@link Documentation }
     * 
     */
    public Documentation createDocumentation() {
        return new Documentation();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link Dictionary }
     * 
     */
    public Dictionary createDictionary() {
        return new Dictionary();
    }

    /**
     * Create an instance of {@link UnitList }
     * 
     */
    public UnitList createUnitList() {
        return new UnitList();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link Appinfo }
     * 
     */
    public Appinfo createAppinfo() {
        return new Appinfo();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link Definition }
     * 
     */
    public Definition createDefinition() {
        return new Definition();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Alternative }
     * 
     */
    public Alternative createAlternative() {
        return new Alternative();
    }

    /**
     * Create an instance of {@link Enumeration }
     * 
     */
    public Enumeration createEnumeration() {
        return new Enumeration();
    }

    /**
     * Create an instance of {@link RelatedEntry }
     * 
     */
    public RelatedEntry createRelatedEntry() {
        return new RelatedEntry();
    }

    /**
     * Create an instance of {@link System }
     * 
     */
    public System createSystem() {
        return new System();
    }

    /**
     * Create an instance of {@link ComplexObject }
     * 
     */
    public ComplexObject createComplexObject() {
        return new ComplexObject();
    }

    /**
     * Create an instance of {@link Spectrum }
     * 
     */
    public Spectrum createSpectrum() {
        return new Spectrum();
    }

    /**
     * Create an instance of {@link Sample }
     * 
     */
    public Sample createSample() {
        return new Sample();
    }

    /**
     * Create an instance of {@link ParameterList }
     * 
     */
    public ParameterList createParameterList() {
        return new ParameterList();
    }

    /**
     * Create an instance of {@link SpectrumData }
     * 
     */
    public SpectrumData createSpectrumData() {
        return new SpectrumData();
    }

    /**
     * Create an instance of {@link Xaxis }
     * 
     */
    public Xaxis createXaxis() {
        return new Xaxis();
    }

    /**
     * Create an instance of {@link Yaxis }
     * 
     */
    public Yaxis createYaxis() {
        return new Yaxis();
    }

    /**
     * Create an instance of {@link PeakList }
     * 
     */
    public PeakList createPeakList() {
        return new PeakList();
    }

    /**
     * Create an instance of {@link Peak }
     * 
     */
    public Peak createPeak() {
        return new Peak();
    }

    /**
     * Create an instance of {@link PeakStructure }
     * 
     */
    public PeakStructure createPeakStructure() {
        return new PeakStructure();
    }

    /**
     * Create an instance of {@link PeakGroup }
     * 
     */
    public PeakGroup createPeakGroup() {
        return new PeakGroup();
    }

    /**
     * Create an instance of {@link TableRowList }
     * 
     */
    public TableRowList createTableRowList() {
        return new TableRowList();
    }

    /**
     * Create an instance of {@link TableRow }
     * 
     */
    public TableRow createTableRow() {
        return new TableRow();
    }

    /**
     * Create an instance of {@link Stmml }
     * 
     */
    public Stmml createStmml() {
        return new Stmml();
    }

    /**
     * Create an instance of {@link Cml }
     * 
     */
    public Cml createCml() {
        return new Cml();
    }

    /**
     * Create an instance of {@link Tcell }
     * 
     */
    public Tcell createTcell() {
        return new Tcell();
    }

    /**
     * Create an instance of {@link Isotope }
     * 
     */
    public Isotope createIsotope() {
        return new Isotope();
    }

    /**
     * Create an instance of {@link Abundance }
     * 
     */
    public Abundance createAbundance() {
        return new Abundance();
    }

    /**
     * Create an instance of {@link MoleculeList }
     * 
     */
    public MoleculeList createMoleculeList() {
        return new MoleculeList();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link ArrayList }
     * 
     */
    public ArrayList createArrayList() {
        return new ArrayList();
    }

    /**
     * Create an instance of {@link TableHeader }
     * 
     */
    public TableHeader createTableHeader() {
        return new TableHeader();
    }

    /**
     * Create an instance of {@link TableHeaderCell }
     * 
     */
    public TableHeaderCell createTableHeaderCell() {
        return new TableHeaderCell();
    }

    /**
     * Create an instance of {@link LatticeVector }
     * 
     */
    public LatticeVector createLatticeVector() {
        return new LatticeVector();
    }

    /**
     * Create an instance of {@link Plane3 }
     * 
     */
    public Plane3 createPlane3() {
        return new Plane3();
    }

    /**
     * Create an instance of {@link PotentialForm }
     * 
     */
    public PotentialForm createPotentialForm() {
        return new PotentialForm();
    }

    /**
     * Create an instance of {@link Sphere3 }
     * 
     */
    public Sphere3 createSphere3() {
        return new Sphere3();
    }

    /**
     * Create an instance of {@link UnitTypeList }
     * 
     */
    public UnitTypeList createUnitTypeList() {
        return new UnitTypeList();
    }

    /**
     * Create an instance of {@link Integer }
     * 
     */
    public Integer createInteger() {
        return new Integer();
    }

    /**
     * Create an instance of {@link Float }
     * 
     */
    public Float createFloat() {
        return new Float();
    }

    /**
     * Create an instance of {@link IntegerArray }
     * 
     */
    public IntegerArray createIntegerArray() {
        return new IntegerArray();
    }

    /**
     * Create an instance of {@link StringArray }
     * 
     */
    public StringArray createStringArray() {
        return new StringArray();
    }

    /**
     * Create an instance of {@link Line3 }
     * 
     */
    public Line3 createLine3() {
        return new Line3();
    }

    /**
     * Create an instance of {@link Potential }
     * 
     */
    public Potential createPotential() {
        return new Potential();
    }

    /**
     * Create an instance of {@link ActionList }
     * 
     */
    public ActionList createActionList() {
        return new ActionList();
    }

    /**
     * Create an instance of {@link SpectrumList }
     * 
     */
    public SpectrumList createSpectrumList() {
        return new SpectrumList();
    }

    /**
     * Create an instance of {@link KpointList }
     * 
     */
    public KpointList createKpointList() {
        return new KpointList();
    }

    /**
     * Create an instance of {@link Kpoint }
     * 
     */
    public Kpoint createKpoint() {
        return new Kpoint();
    }

    /**
     * Create an instance of {@link PotentialList }
     * 
     */
    public PotentialList createPotentialList() {
        return new PotentialList();
    }

    /**
     * Create an instance of {@link BandList }
     * 
     */
    public BandList createBandList() {
        return new BandList();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link AtomicBasisFunction }
     * 
     */
    public AtomicBasisFunction createAtomicBasisFunction() {
        return new AtomicBasisFunction();
    }

    /**
     * Create an instance of {@link String }
     * 
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link Point3 }
     * 
     */
    public Point3 createPoint3() {
        return new Point3();
    }

    /**
     * Create an instance of {@link Trow }
     * 
     */
    public Trow createTrow() {
        return new Trow();
    }

    /**
     * Create an instance of {@link ReactionList }
     * 
     */
    public ReactionList createReactionList() {
        return new ReactionList();
    }

    /**
     * Create an instance of {@link IsotopeList }
     * 
     */
    public IsotopeList createIsotopeList() {
        return new IsotopeList();
    }

    /**
     * Create an instance of {@link FloatArray }
     * 
     */
    public FloatArray createFloatArray() {
        return new FloatArray();
    }

    /**
     * Create an instance of {@link FragmentList }
     * 
     */
    public FragmentList createFragmentList() {
        return new FragmentList();
    }

    /**
     * Create an instance of {@link Fragment }
     * 
     */
    public Fragment createFragment() {
        return new Fragment();
    }

    /**
     * Create an instance of {@link Eigen }
     * 
     */
    public Eigen createEigen() {
        return new Eigen();
    }

    /**
     * Create an instance of {@link BasisSet }
     * 
     */
    public BasisSet createBasisSet() {
        return new BasisSet();
    }

    /**
     * Create an instance of {@link Lattice }
     * 
     */
    public Lattice createLattice() {
        return new Lattice();
    }

}
