//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 04:17:37 PM BST 
//


package uk.ac.cam.ceb.como.io.chem.file.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * 
 *                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;h:div xmlns:h="http://www.w3.org/1999/xhtml"&gt;
 *                     &lt;h:p&gt;The semantics of the content model are&lt;/h:p&gt;
 *                     &lt;h:ul&gt;&lt;h:li&gt;metadataList for general metadata&lt;/h:li&gt;&lt;h:li&gt;label for classifying or describing the reaction (e.g. "hydrolysis")&lt;/h:li&gt;&lt;h:li&gt;identifier for unique identification. This could be a classification such as EC (enzyme commission) or an IChI-like string generated from the components.&lt;/h:li&gt;&lt;h:li&gt;these are followed by the possible components of the reaction and/or a reactionList of further details.&lt;/h:li&gt;
 *                     &lt;/h:ul&gt;.&lt;/h:div&gt;
 * </pre>
 * 
 * 
 *             
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.xml-cml.org/schema}metadataList" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema}label" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.xml-cml.org/schema}name" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}identifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.xml-cml.org/schema}reactiveCentre" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}mechanism" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}reactantList" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}spectatorList" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}substanceList" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}conditionList" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}transitionState" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}productList" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}propertyList" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}map" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema}object" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}title"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}state"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}atomMap"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}electronMap"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}convention"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}reactionFormat"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}id"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}dictRef"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}reactionType"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}yield"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}ref"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}bondMap"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}reactionRole"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadataList",
    "label",
    "nameOrIdentifier",
    "reactiveCentreAndMechanismAndReactantList"
})
@XmlRootElement(name = "reaction")
public class Reaction {

    protected List<MetadataList> metadataList;
    protected List<Label> label;
    @XmlElements({
        @XmlElement(name = "name", type = Name.class),
        @XmlElement(name = "identifier", type = Identifier.class)
    })
    protected List<java.lang.Object> nameOrIdentifier;
    @XmlElements({
        @XmlElement(name = "reactiveCentre", type = ReactiveCentre.class),
        @XmlElement(name = "mechanism", type = Mechanism.class),
        @XmlElement(name = "reactantList", type = ReactantList.class),
        @XmlElement(name = "spectatorList", type = SpectatorList.class),
        @XmlElement(name = "substanceList", type = SubstanceList.class),
        @XmlElement(name = "conditionList", type = ConditionList.class),
        @XmlElement(name = "transitionState", type = TransitionState.class),
        @XmlElement(name = "productList", type = ProductList.class),
        @XmlElement(name = "propertyList", type = PropertyList.class),
        @XmlElement(name = "map", type = Map.class),
        @XmlElement(name = "object", type = uk.ac.cam.ceb.como.io.chem.file.jaxb.Object.class)
    })
    protected List<java.lang.Object> reactiveCentreAndMechanismAndReactantList;
    @XmlAttribute(name = "title")
    protected java.lang.String title;
    @XmlAttribute(name = "state")
    protected java.lang.String state;
    @XmlAttribute(name = "atomMap")
    protected java.lang.String atomMap;
    @XmlAttribute(name = "electronMap")
    protected java.lang.String electronMap;
    @XmlAttribute(name = "convention")
    protected java.lang.String convention;
    @XmlAttribute(name = "format")
    protected java.lang.String format;
    @XmlAttribute(name = "id")
    protected java.lang.String id;
    @XmlAttribute(name = "dictRef")
    protected java.lang.String dictRef;
    @XmlAttribute(name = "type")
    protected java.lang.String type;
    @XmlAttribute(name = "yield")
    protected Double yield;
    @XmlAttribute(name = "ref")
    protected java.lang.String ref;
    @XmlAttribute(name = "bondMap")
    protected QName bondMap;
    @XmlAttribute(name = "role")
    protected java.lang.String role;

    /**
     * Gets the value of the metadataList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataList }
     * 
     * 
     */
    public List<MetadataList> getMetadataList() {
        if (metadataList == null) {
            metadataList = new ArrayList<MetadataList>();
        }
        return this.metadataList;
    }

    /**
     * Gets the value of the label property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getLabel() {
        if (label == null) {
            label = new ArrayList<Label>();
        }
        return this.label;
    }

    /**
     * Gets the value of the nameOrIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameOrIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameOrIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Name }
     * {@link Identifier }
     * 
     * 
     */
    public List<java.lang.Object> getNameOrIdentifier() {
        if (nameOrIdentifier == null) {
            nameOrIdentifier = new ArrayList<java.lang.Object>();
        }
        return this.nameOrIdentifier;
    }

    /**
     * Gets the value of the reactiveCentreAndMechanismAndReactantList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reactiveCentreAndMechanismAndReactantList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReactiveCentreAndMechanismAndReactantList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReactiveCentre }
     * {@link Mechanism }
     * {@link ReactantList }
     * {@link SpectatorList }
     * {@link SubstanceList }
     * {@link ConditionList }
     * {@link TransitionState }
     * {@link ProductList }
     * {@link PropertyList }
     * {@link Map }
     * {@link uk.ac.cam.ceb.como.io.chem.file.jaxb.Object }
     * 
     * 
     */
    public List<java.lang.Object> getReactiveCentreAndMechanismAndReactantList() {
        if (reactiveCentreAndMechanismAndReactantList == null) {
            reactiveCentreAndMechanismAndReactantList = new ArrayList<java.lang.Object>();
        }
        return this.reactiveCentreAndMechanismAndReactantList;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setTitle(java.lang.String value) {
        this.title = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setState(java.lang.String value) {
        this.state = value;
    }

    /**
     * Gets the value of the atomMap property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAtomMap() {
        return atomMap;
    }

    /**
     * Sets the value of the atomMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAtomMap(java.lang.String value) {
        this.atomMap = value;
    }

    /**
     * Gets the value of the electronMap property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getElectronMap() {
        return electronMap;
    }

    /**
     * Sets the value of the electronMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setElectronMap(java.lang.String value) {
        this.electronMap = value;
    }

    /**
     * Gets the value of the convention property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getConvention() {
        return convention;
    }

    /**
     * Sets the value of the convention property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setConvention(java.lang.String value) {
        this.convention = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFormat(java.lang.String value) {
        this.format = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dictRef property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDictRef() {
        return dictRef;
    }

    /**
     * Sets the value of the dictRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDictRef(java.lang.String value) {
        this.dictRef = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setType(java.lang.String value) {
        this.type = value;
    }

    /**
     * Gets the value of the yield property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYield() {
        return yield;
    }

    /**
     * Sets the value of the yield property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYield(Double value) {
        this.yield = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setRef(java.lang.String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the bondMap property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getBondMap() {
        return bondMap;
    }

    /**
     * Sets the value of the bondMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setBondMap(QName value) {
        this.bondMap = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setRole(java.lang.String value) {
        this.role = value;
    }

}
