//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 04:17:37 PM BST 
//


package uk.ac.cam.ceb.como.io.chem.file.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.xml-cml.org/schema}metadata"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema}metadataList"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema}description"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema}annotation"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema}definition" minOccurs="0"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema}unit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema}unitType" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}symbol"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}constantToSI"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}id"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}parentSI"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}multiplierToData"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}title"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}unitType"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}abbreviation"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}isSI"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}power"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}name"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}multiplierToSI"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}units"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadataOrMetadataListOrDescription"
})
@XmlRootElement(name = "unit")
public class Unit {

    @XmlElements({
        @XmlElement(name = "metadata", type = Metadata.class),
        @XmlElement(name = "metadataList", type = MetadataList.class),
        @XmlElement(name = "description", type = Description.class),
        @XmlElement(name = "annotation", type = Annotation.class),
        @XmlElement(name = "definition", type = Definition.class),
        @XmlElement(name = "unit", type = Unit.class),
        @XmlElement(name = "unitType", type = UnitType.class)
    })
    protected List<java.lang.Object> metadataOrMetadataListOrDescription;
    @XmlAttribute(name = "symbol")
    protected java.lang.String symbol;
    @XmlAttribute(name = "constantToSI")
    protected Double constantToSI;
    @XmlAttribute(name = "id")
    protected java.lang.String id;
    @XmlAttribute(name = "parentSI")
    protected java.lang.String parentSI;
    @XmlAttribute(name = "multiplierToData")
    protected Double multiplierToData;
    @XmlAttribute(name = "title")
    protected java.lang.String title;
    @XmlAttribute(name = "unitType")
    protected java.lang.String unitType;
    @XmlAttribute(name = "abbreviation")
    protected java.lang.String abbreviation;
    @XmlAttribute(name = "isSI")
    protected Boolean isSI;
    @XmlAttribute(name = "power")
    protected Double power;
    @XmlAttribute(name = "name")
    protected java.lang.String name;
    @XmlAttribute(name = "multiplierToSI")
    protected Double multiplierToSI;
    @XmlAttribute(name = "units")
    protected java.lang.String units;

    /**
     * Gets the value of the metadataOrMetadataListOrDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataOrMetadataListOrDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataOrMetadataListOrDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Metadata }
     * {@link MetadataList }
     * {@link Description }
     * {@link Annotation }
     * {@link Definition }
     * {@link Unit }
     * {@link UnitType }
     * 
     * 
     */
    public List<java.lang.Object> getMetadataOrMetadataListOrDescription() {
        if (metadataOrMetadataListOrDescription == null) {
            metadataOrMetadataListOrDescription = new ArrayList<java.lang.Object>();
        }
        return this.metadataOrMetadataListOrDescription;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSymbol(java.lang.String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the constantToSI property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getConstantToSI() {
        return constantToSI;
    }

    /**
     * Sets the value of the constantToSI property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setConstantToSI(Double value) {
        this.constantToSI = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parentSI property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getParentSI() {
        return parentSI;
    }

    /**
     * Sets the value of the parentSI property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setParentSI(java.lang.String value) {
        this.parentSI = value;
    }

    /**
     * Gets the value of the multiplierToData property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getMultiplierToData() {
        if (multiplierToData == null) {
            return  1.0D;
        } else {
            return multiplierToData;
        }
    }

    /**
     * Sets the value of the multiplierToData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMultiplierToData(Double value) {
        this.multiplierToData = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setTitle(java.lang.String value) {
        this.title = value;
    }

    /**
     * Gets the value of the unitType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getUnitType() {
        return unitType;
    }

    /**
     * Sets the value of the unitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setUnitType(java.lang.String value) {
        this.unitType = value;
    }

    /**
     * Gets the value of the abbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAbbreviation() {
        return abbreviation;
    }

    /**
     * Sets the value of the abbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAbbreviation(java.lang.String value) {
        this.abbreviation = value;
    }

    /**
     * Gets the value of the isSI property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSI() {
        return isSI;
    }

    /**
     * Sets the value of the isSI property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSI(Boolean value) {
        this.isSI = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPower(Double value) {
        this.power = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

    /**
     * Gets the value of the multiplierToSI property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMultiplierToSI() {
        return multiplierToSI;
    }

    /**
     * Sets the value of the multiplierToSI property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMultiplierToSI(Double value) {
        this.multiplierToSI = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setUnits(java.lang.String value) {
        this.units = value;
    }

}
