package uk.ac.cam.cares.jps.thermo.sparql;

public class QueryString {

	/**
	 * 
	 * @param uuid
	 * @return String sparql query that contains given uuid as input parameter. Result of this query are data that are input for thermo calculations implemented in Python. 
	 * 
	 */
	public static String getAllTriplesForThermoCalculation(String uuid) {
		
		String query="PREFIX compchemkb: <https://como.cheng.cam.ac.uk/kb/compchem.owl#>"
			+"PREFIX gc: <http://purl.org/gc/>"
				+"PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>"
				+"PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>"
				+"SELECT ?g09 ?speciesIRI ?moleculeName ?atomName ?atomNumber ?levelOfTheory ?basisSetValue ?frequenciesSize ?frequenciesValue ?frequenciesUnit ?spinMultiplicityValue  ?coordinateX ?coordinateY ?coordinateZ ?massValue ?massUnit ?geometryTypeValue ?rotationalConstantsSize ?rotationalConstantsUnit ?rotationalConstantsValue ?rotationalSymmetryNumber ?programName ?programVersion ?runDate " 
				+"WHERE { " 
				+"{ "
				+"?g09 compchemkb:hasInitialization ?mn0 . " 
				+"?mn0 gc:hasMoleculeProperty ?mp0 . " 
				+"?mp0 gc:hasName ?moleculeName . " 
				+"} "
				+ "UNION"
				+ "{"
				+"?g09 compchemkb:hasUniqueSpeciesIRI ?speciesIRI . "
				+ "}"
				+"UNION "
				+"{ "
				+"?g09 compchemkb:hasInitialization ?mn1 . " 
				+"?mn1 gc:hasMoleculeProperty ?mp1 .  "
				+"?mp1 gc:hasMolecule ?mol0 . "
				+"?mol0 gc:hasNumberOfAtoms ?atomNumber. "
				+"?mol0 gc:hasAtom ?at0 . "
				+"?at0 gc:isElement ?atomName . " 
				+"}"
				+"UNION"
				+"{"
				+"?g09 compchemkb:hasInitialization ?mn2 . "
				+"?mn2 gc:hasParameter ?p1 . "
				+"?p1 rdf:type <https://como.cheng.cam.ac.uk/kb/compchem.owl#LevelOfTheory> . "
				+"?p1 compchemkb:hasLevelOfTheory ?levelOfTheory . "
				+"?mn2 gc:hasParameter ?p2 . "
				+"?p2 rdf:type <http://purl.org/gc/BasisSet> . "
				+"?p2 gc:hasBasisSet ?basisSetValue . "
				+"}"
				+"UNION "
				+"{ "
				+"?g09 gc:isCalculationOn ?go. " 
				+"?go rdf:type gc:GeometryOptimization . "
				+"?go gc:hasMolecule ?mol1. "
				+"?mol1 gc:hasAtom ?at1 . "
				+"?at1 gc:isElement ?atomName . " 
				+"?at1 gc:hasAtomCoordinateX ?x . ?x gc:hasValue ?coordinateX. "
				+"?at1 gc:hasAtomCoordinateY ?y . ?y gc:hasValue ?coordinateY. "
				+"?at1 gc:hasAtomCoordinateZ ?z . ?z gc:hasValue ?coordinateZ. "
				+"?at1 gc:hasMass ?mass . ?mass gc:hasValue ?massValue .  "
				+"?mass gc:hasUnit ?massUnit . "
				+"}"
				+ "UNION"
				+"{"
				+"?g09 gc:isCalculationOn ?go1. "
				+"?go1 rdf:type gc:GeometryOptimization . "
				+"?go1 gc:hasMolecule ?mol2. "
				+"?mol2 compchemkb:hasSpinMultiplicity ?spinMultiplicityValue . "
				+"} "
				+"UNION"
				+"{"
				+"?g09 gc:isCalculationOn ?go2. "
				+"?go2 rdf:type gc:VibrationalAnalysis. " 
				+"?go2 gc:hasResult ?r . "
				+"?r rdf:type gc:Frequency . "
				+"?r gc:hasVibrationCount ?frequenciesSize . "
				+"?r compchemkb:hasFrequencies ?frequenciesValue . "
				+"?r gc:hasUnit ?frequenciesUnit. "
				+"}"
				+"UNION"
				+"{"
				+"?g09 gc:isCalculationOn ?go3. " 
				+"?go3 a compchemkb:GeometryType . "
				+"?go3 compchemkb:hasGeometryType ?geometryTypeValue. "
				+"}"
				+"UNION"
				+"{"
				+"?g09 gc:isCalculationOn ?go4. "
				+"?go4 rdf:type compchemkb:RotationalConstants . "
				+"?go4 compchemkb:hasRotationalConstants ?rotationalConstantsValue . "
				+"?go4 gc:hasUnit ?rotationalConstantsUnit .  "
				+"?go compchemkb:hasRotationalConstantsCount ?rotationalConstantsSize . "
				+"}"
				+"UNION"
				+"{"
				+"?g09 gc:isCalculationOn ?go5. "
				+"?go5 rdf:type compchemkb:RotationalSymmetry . "
				+"?go5 compchemkb:hasRotationalSymmetryNumber ?rotationalSymmetryNumber . "
				+"}"
				+"UNION"
				+"{"
				+"?g09 compchemkb:hasEnvironment ?env . "
				+"?env compchemkb:hasProgram ?programName . "  
				+"?env compchemkb:hasProgramVersion ?programVersion . "
				+"?env compchemkb:hasRunDate ?runDate . "
				+"} "
				+ "FILTER(str(?g09)='"+uuid+"')"
				+ "}";

		return query;
	}
	
}