# This module provides a mapping of expected units for all optimisation time 
# series inputs, to ensure they are queried from KG in compliant units

from .iris import *

UNITS = {
    # cost
    OHN_GAS_UNIT_COST: OM_EURO_PER_MEGAWATTHOUR,
    OHN_ELECTRICITY_SPOT_PRICE: OM_EURO_PER_MEGAWATTHOUR,
    OHN_CO2_CERTIFICATE_PRICE: OM_EURO_PER_TONNE,
    OHN_CHP_BONUS: OM_EURO_PER_MEGAWATTHOUR,
    OHN_GRID_CHARGES: OM_EURO_PER_MEGAWATTHOUR,
    OHN_DEMAND_DRIVEN_WEAR_COST: OM_EURO_PER_MEGAWATTHOUR,
    OHN_HOURLY_WEAR_COST: OM_EURO_PER_HOUR,
    OHN_HOURLY_LABOUR_COST: OM_EURO_PER_HOUR,   
    # heating network
    OM_VOLUMETRICFLOWRATE: OM_M3_PER_HOUR,
    OM_TEMPERATURE: OM_CELSIUS,
    OM_PRESSURE: OM_BAR, 
    # generators
    OHN_AVAILABILITY: None,
    OM_POWER: OM_MEGAWATT,
    OHN_PROVIDED_HEAT_AMOUNT: OM_MEGAWATTHOUR,       
    OHN_GENERATED_HEAT_AMOUNT: OM_MEGAWATTHOUR,
    OHN_HEAT_DEMAND: OM_MEGAWATTHOUR,   
}
