PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix om:  <http://www.ontology-of-units-of-measure.org/resource/om-2/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

prefix ts: <https://www.theworldavatar.com/kg/ontotimeseries/>
prefix ontobms: <https://www.theworldavatar.com/kg/ontobms/>
prefix saref: <https://saref.etsi.org/core/>
prefix ontodevice: <https://www.theworldavatar.com/kg/ontodevice/>
prefix : <https://www.theworldavatar.com/kg/ontobms/>
SELECT distinct ?Measurement ?Name ?Unit WHERE {
  {
    [IRI] saref:consistsOf ?sensors1 .

    ?sensors1 ontodevice:measures ?m.
    ?m om:hasValue ?Measurement.
   	?Measurement om:hasUnit ?u.
    BIND (replace(str(?Measurement), str(ontobms:), "") as ?Name).
    BIND (replace(str(?u), str(om:), "") as ?Unit).
  } union {
    [IRI] saref:consistsOf ?sensors1 .

    ?sensors1 ontodevice:observes ?Measurement.
    BIND (replace(str(?Measurement), str(ontobms:), "") as ?Name).
    BIND ("" as ?Unit).
  } union {
    [IRI] saref:consistsOf ?sensors1 .
    ?sensors1 ontodevice:sendsSignalTo ?vav.
    ?vav saref:consistsOf ?sensors2.

    ?sensors2 ontodevice:measures ?m.
    ?m om:hasValue ?Measurement.
    ?m rdf:type ?type.
    ?Measurement om:hasUnit ?u.
    BIND (replace(str(?type), str(om:), "") as ?Name).
    BIND (replace(str(?u), str(om:), "") as ?Unit).
  } union {
    [IRI] saref:consistsOf ?sensors1 .
    ?sensors1 ontodevice:sendsSignalTo ?vav.
    ?vav saref:consistsOf ?sensors2.

    ?sensors2 ontodevice:observes ?Measurement.
    ?Measurement rdf:type ?type.
    BIND (replace(str(?type), str(ontobms:), "") as ?Name).
    BIND ("" as ?unit).
  }
}