<%@ page language="java"
         contentType="text/html; charset=US-ASCII"
         pageEncoding="US-ASCII"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "https://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src='./test-summary.js' type='text/javascript'></script>
        <link href='./style.css' type='text/css' rel='stylesheet'>

        <title>Summary:</title>

        <%@ page import="uk.ac.cam.cares.jps.agent.status.TemplateHandler" %>
        <%@ page import="uk.ac.cam.cares.jps.agent.status.define.*" %>
        <%@ page import="uk.ac.cam.cares.jps.agent.status.record.*" %>

        <%@ page import="java.util.List" %>
    </head>
    <body onload="initialise()">
        <div id="preamble">
            <div id="title">
                <h1>Test Summary - Dashboard</h1>
            </div>
            <div id="introduction">
                <p>
                    This page shows the result of recent executions of this individual test case. Select one of the result boxes below to view the log generated by that test execution.
                </p>
                <p>
                    This test is defined by the following variables within the StatusAgent:
                </p>
                <div style="padding-left: 50px; color: grey;">
                    <%
                        String testDetails = (String) request.getAttribute("test-details");
                        out.print(testDetails);
                    %>
                </div>
            </div>
        </div>
        <div class="all-records-container">
            <%
                // Get the list of execution records
                List<TestRecord> records = (List<TestRecord>) request.getAttribute("test-records");

                out.print("<div class='record-container'>");
                out.print("<div class='record-container-title center-text'>");
                out.print("<h3>Recent Executions</h3>");
                out.print("</div>");

                // For each individual test
                for (TestRecord record : records) {
                    TestDefinition definition = record.getDefinition();
                    out.print(TemplateHandler.getSummaryStub(pageContext.getServletContext(), definition, record));
                }
                out.print("</div>");
            %>
        </div>
        <div class="log-container">
            <div class="log-placehold center-text">
                <p>Select a test execution on the left to view the corresponding log file.</p>
            </div>
        </div>
        <div class="button-container">
            <div class="dashboard-button center-text" onclick="toDashboard()"><p>< Back to Dashboard</p></div>
            <div class="run-test-button center-text" onclick="runTest(this)" 
                 data-test="<% out.print(request.getAttribute("test-name")); %>"
                 data-type="<% out.print(request.getAttribute("test-type"));%>">
                <p>Run Test Now</p>
            </div>
        </div>
    </body>
</html>