package uk.ac.cam.cares.jps.agent.ceatasks;

import java.util.ArrayList;
import java.util.List;

public class CEAOutputData {
    public ArrayList<ArrayList<String>> GridConsumption = new ArrayList<>();
    public ArrayList<ArrayList<String>> ElectricityConsumption = new ArrayList<>();
    public ArrayList<ArrayList<String>> HeatingConsumption = new ArrayList<>();
    public ArrayList<ArrayList<String>> CoolingConsumption = new ArrayList<>();
    public ArrayList<String> RoofSolarSuitableArea = new ArrayList<>();
    public ArrayList<String> SouthWallSolarSuitableArea = new ArrayList<>();
    public ArrayList<String> NorthWallSolarSuitableArea = new ArrayList<>();
    public ArrayList<String> EastWallSolarSuitableArea = new ArrayList<>();
    public ArrayList<String> WestWallSolarSuitableArea = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVRoofSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVWallSouthSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVWallNorthSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVWallEastSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVWallWestSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateRoofESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateWallSouthESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateWallNorthESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateWallEastESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateWallWestESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateRoofQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateWallSouthQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateWallNorthQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateWallEastQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTPlateWallWestQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeRoofESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeWallSouthESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeWallNorthESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeWallEastESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeWallWestESupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeRoofQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeWallSouthQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeWallNorthQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeWallEastQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> PVTTubeWallWestQSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalPlateRoofSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalPlateWallSouthSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalPlateWallNorthSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalPlateWallEastSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalPlateWallWestSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalTubeRoofSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalTubeWallSouthSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalTubeWallNorthSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalTubeWallEastSupply = new ArrayList<>();
    public ArrayList<ArrayList<String>> ThermalTubeWallWestSupply = new ArrayList<>();
    public String targetUrl;
    public ArrayList<String> iris = new ArrayList<>();
    public List<String> times = new ArrayList<>();
}
