from ontomatch.matchers.MeronymRematcher import *
from ontomatch.matchers.BOWMatcher import  *
from ontomatch.matchers.domainMatcher import *
from ontomatch.matchers.StringMatcher import *
from ontomatch.matchers.valueMatcher import *
from ontomatch.matchers.elementMatcher import *
from ontomatch.matchers.instanceStringMatcher import *
from ontomatch.matchers.instanceBOWMatcher import *
from ontomatch.matchers.GeoAttrFinder import *
from ontomatch.matchers.Penalizer import *
