PREFIX credo: <http://theworldavatar.com/ontology/ontocredo/ontocredo.owl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select ?propertyLabel ?value
{ SERVICE [ONTOP] {[IRI] ?hasProperty ?property. ?property ?hasValue ?value.}
  ?hasValue rdfs:subPropertyOf* credo:hasValue;
            rdfs:label ?propertyLabel.
  ?hasProperty rdfs:subPropertyOf* credo:hasProperty}