PREFIX credo: <http://theworldavatar.com/ontology/ontocredo/ontocredo.owl#>
select ?label ?value
WHERE
{{SERVICE [ONTOP] {[IRI] ?hasProperty ?property. ?property ?hasValue ?value .}
  ?hasProperty rdfs:subPropertyOf* credo:hasProperty.
  ?hasValue rdfs:subPropertyOf* credo:hasValue;
            rdfs:label ?label.}
UNION
{{SERVICE [ONTOP] {[IRI] ?hasValue ?value .}
  ?hasValue rdfs:subPropertyOf* credo:hasValue;
            rdfs:label ?label.}}
}
