from .doeagent_properties import (
    TRIPLE_STORE_UPLOAD_SERVER,
    TRIPLE_STORE_UPLOAD_REPOSITORY,
    SPARQL_QUERY_ENDPOINT,
    SPARQL_UPDATE_ENDPOINT,
    PERIODIC_TIMESCALE,
    NAMESPACE_KB_ONTORXN,
    DOEAGENT_ONTOAGENT_SERVICE,
    DOEAGENT_INPUT_JSON_KAY,
    DERIVATION_INSTANCE_BASE_URL,
)
