PREFIX obe:  <https://www.theworldavatar.com/kg/ontobuiltenv/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ppi:	 <http://landregistry.data.gov.uk/def/ppi/>

SELECt ?property ?location
WHERE
{
	?property  rdf:type/rdfs:subClassOf* obe:Property ; 
               # Initially only properties with available transaction record
               # have been considered to identify buildings within the flood
               # polygon; this is obviously not correct --> comment out
               #obe:hasLatestTransactionRecord ?tx ; 
               obe:hasWGS84LatitudeLongitude ?location
}