ABSTRACT_PROPERTY_KEY = "PropertyName"
ABSTRACT_IDENTIFIER_KEY = "IdentifierName"
PROPERTY_KEYS = [
    "AtomChiralCount",
    "AtomChiralDefCount",
    "AtomChiralUndefCount",
    "BondChiralCount",
    "BondChiralDefCount",
    "BondChiralUndefCount",
    # "CanonicalizedCompound",
    "Charge",
    "CompoundComplexity",
    "CovalentUnitCount",
    "ExactMass",
    "HeavyAtomCount",
    "HydrogenBondAcceptorCount",
    "HydrogenBondDonorCount",
    "IsotopeAtomCount",
    "MolecularWeight",
    "MonoIsotopicWeight",
    "RotatableBondCount",
    # "SubStructureKeysFingerprint",
    "TautomerCount",
    "XLogP3",
    "AutoignitionTemperature",
    "Caco2Permeability",
    "CollisionCrossSection",
    "Hydrophobicity",
    "IonizationPotential",
    "IsoelectricPoint",
    "LogP",
    "LogS",
    "PolarSurfaceArea",
    "BoilingPoint",
    "Density",
    "DissociationConstants",
    "EnthalpyOfSublimation",
    "FlashPoint",
    "StandardEnthalpyOfFormation",
    "HeatOfCombustion",
    "HeatOfVaporization",
    "HenrysLawConstant",
    "MeltingPoint",
    "OpticalRotation",
    "Solubility",
    "SurfaceTension",
    "VaporDensity",
    "VaporPressure",
    "Viscosity",
    "HeatCapacity",
    "StandardEnthalpy",
    "StandardEntropy"
]

IDENTIFIER_KEYS = [
    "ChebiID",
    "CID",
    "EmpiricalFormula",
    "InChI",
    "InChIKey",
    "IUPACName",
    "MolecularFormula",
    "SMILES",
]

USE_KEY = "Use"
CHEMCLASS_KEY = "ChemicalClass"