prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: 	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix eip0:   	<http://www.theworldavatar.com/ontology/ontoeip/upper_level/system_v1.owl#>
prefix eip1:  	<http://www.theworldavatar.com/ontology/ontoeip/powerplants/PowerPlant.owl#>
prefix eip3:   	<http://www.theworldavatar.com/ontology/ontocape/upper_level/technical_system.owl#>
prefix cape0:	<http://www.theworldavatar.com/ontology/ontocape/upper_level/system.owl#>

SELECT ?Property ?Value ?Unit WHERE {
	SERVICE [ONTOP] {
		{
			BIND ("Name" AS ?Property)
			[IRI] eip0:hasName ?Value .
		} UNION {
			BIND ("Owner" AS ?Property)
			[IRI] eip0:isOwnedBy/eip0:hasName ?Value .
		} UNION {
			BIND ("Year Commissioned" AS ?Property)
			[IRI] eip1:hasYearBuilt/cape0:hasValue/cape0:numericalValue ?Value .
		} UNION {
			BIND ("Grid Connection Type" AS ?Property)
			[IRI] eip0:hasGridConnection ?Value .
		} UNION {
			BIND ("Is Combined Heat & Power" AS ?Property)
			[IRI] eip0:isCombinedHeatPower ?Value .
		} UNION {
			BIND ("Plant Type" AS ?Property)
			[IRI] eip0:hasType ?Value .
		} UNION {
			BIND ("Primary Technology" AS ?Property)
			[IRI] eip3:hasFunctionalAspect/eip0:usesGenerationTechnology/rdfs:label ?Value .
		} UNION {
			BIND ("Primary Fuel" AS ?Property)
			[IRI] eip3:hasFunctionalAspect/eip0:consumesPrimaryFuel/rdfs:label ?Value .
		} UNION {
			BIND ("Secondary Fuel" AS ?Property)
			[IRI] eip3:hasFunctionalAspect/eip0:consumesSecondaryFuel/rdfs:label ?Value .
		} UNION {
			BIND ("Installed Capacity" AS ?Property)
			BIND ("MW" AS ?Unit)
			[IRI] eip3:hasRequirementsAspect/cape0:hasValue/cape0:numericalValue ?Value .
		} UNION {
            BIND ("Nearby Population (1 KM)" AS ?Property)
            [IRI] eip1:hasPopulationInRadius ?temp
            BIND (ROUND(?temp) AS ?Value) .
        }
	}
}
