POST http://localhost:3838/buildingidentificationagent/postgis
content-type: application/json
{
    "maxDistance": "300.0",
    "table": "data_centres",
    "column": "wkb_geometry",
    "oneToMany": "false",
    "mapping": "industry_buildings.obda"
}