PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX osm: <https://w3id.org/openstreetmap/terms#>
PREFIX openstreetmap: <https://www.openstreetmap.org/>
PREFIX ontosl:    <https://www.theworldavatar.com/kg/ontosealevel/>
PREFIX om:     <http://www.ontology-of-units-of-measure.org/resource/om-2/>

SELECT * WHERE {
  ?sub a osm:Way. 
  ?sub ontosl:hasLength ?length. 
  ?length om:hasValue ?value. 
  ?value om:hasNumericalValue ?numvalue.
} 
LIMIT 10