# URLs to ontology .owl files
TBOX_URL = 'https://github.com/cambridge-cares/TheWorldAvatar/raw/main/JPS_Ontology/ontology/ontoflood/OntoFlood TBox.owl'
ABOX_URL = 'https://github.com/cambridge-cares/TheWorldAvatar/raw/main/JPS_Ontology/ontology/ontoflood/OntoFlood ABox.owl'

###--- Common Base URLs ---###
# External ontologies
RDF = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
RDFS = 'http://www.w3.org/2000/01/rdf-schema#'
XSD = 'http://www.w3.org/2001/XMLSchema#'
GEO = 'http://www.opengis.net/ont/geosparql#'
OM = 'http://www.ontology-of-units-of-measure.org/resource/om-2/'
OWL = 'http://www.w3.org/2002/07/owl#'
TIME = 'https://www.w3.org/2006/time#'
RT = 'http://environment.data.gov.uk/flood-monitoring/def/core/'
ENVO = 'http://purl.obolibrary.org/obo/'
SOPH = 'http://sweetontology.net/phen/'
SOPHHY = 'http://sweetontology.net/phenHydro/'
# CoMo / CARES ontologies
FLOOD = 'https://www.theworldavatar.com/kg/ontoflood/'
BUILT = 'https://www.theworldavatar.com/kg/ontobuiltenv/'
TS = 'https://www.theworldavatar.com/kg/ontotimeseries/'
# Knowledge base
KB = 'https://www.theworldavatar.com/kg/ontoflood/'

###--- IRIs for OntoFlood ---###
# TBox
FLOOD_ADMINISTRATIVEDISTRICT = FLOOD + 'AdministrativeDistrict'        
FLOOD_AFFECTS = FLOOD + 'affects'
FLOOD_AREALDISTRIBUTION = FLOOD + 'ArealDistribution'
FLOOD_AREALEXTENTPOLYGON = FLOOD + 'ArealExtentPolygon'
FLOOD_AREALINFRASTRUCTURE = FLOOD + 'ArealInfrastructure'
FLOOD_ATTACHEDWATERBODY = FLOOD + 'attachedWaterBody'
FLOOD_BUILDING = FLOOD + 'Building'
FLOOD_COASTALWATER = FLOOD + 'CoastalWater'
FLOOD_COMMERCIALAREA = FLOOD + 'CommercialArea'
FLOOD_ENVIRONMENTALCOMPONENT = FLOOD + 'EnvironmentalComponent'        
#FLOOD_FLOODALERT = FLOOD + 'FloodAlert'
FLOOD_FLOODALERTORWARNINGHISTORY = FLOOD + 'FloodAlertOrWarningHistory'
FLOOD_FLOODDEPTH = FLOOD + 'FloodDepth'
FLOOD_FLOODFORECAST = FLOOD + 'FloodForecast'
FLOOD_FLOODSOURCE = FLOOD + 'FloodSource'
#FLOOD_FLOODWARNING = FLOOD + 'FloodWarning'
FLOOD_GROUNDWATER = FLOOD + 'GroundWater'
FLOOD_HASADMINISTRATIVEDISTRICT = FLOOD + 'hasAdministrativeDistrict'  
FLOOD_HASALERTORWARNINGHISTORY = FLOOD + 'hasAlertOrWarningHistory'    
FLOOD_HASAREAIDENTIFIER = FLOOD + 'hasAreaIdentifier'
FLOOD_HASAREALEXTENT = FLOOD + 'hasArealExtent'
FLOOD_HASCLASSIFICATION = FLOOD + 'hasClassification'
FLOOD_HASEFFECTIVEDATE = FLOOD + 'hasEffectiveDate'
FLOOD_HASFLOODSOURCE = FLOOD + 'hasFloodSource'
FLOOD_HASGEOSPATIALDISTRIBUTION = FLOOD + 'hasGeospatialDistribution'  
FLOOD_HASIMPACTLEVEL = FLOOD + 'hasImpactLevel'
FLOOD_HASINTENSITY = FLOOD + 'hasIntensity'
FLOOD_HASLIKELIHOOD = FLOOD + 'hasLikelihood'
FLOOD_HASLIKELIHOODSCORE = FLOOD + 'hasLikelihoodScore'
FLOOD_HASLOCATION = FLOOD + 'hasLocation'
FLOOD_HASMONETARYVALUE = FLOOD + 'hasMonetaryValue'
FLOOD_HASPOTENTIALIMPACT = FLOOD + 'hasPotentialImpact'
FLOOD_HASRISKLEVEL = FLOOD + 'hasRiskLevel'
FLOOD_HASSEVERITY = FLOOD + 'hasSeverity'
FLOOD_HASSEVERITYLEVEL = FLOOD + 'hasSeverityLevel'
FLOOD_HASTIMEINTERVAL = FLOOD + 'hasTimeInterval'
FLOOD_HASTOTALAFFECTEDAREA = FLOOD + 'hasTotalAffectedArea'
FLOOD_HASTOTALCOUNT = FLOOD + 'hasTotalCount'
FLOOD_HASTOTALMONETARYVALUE = FLOOD + 'hasTotalMonetaryValue'
FLOOD_HASWGS84LATITUDELONGITUDE = FLOOD + 'hasWGS84LatitudeLongitude'  
#FLOOD_HIGHLIKELIHOOD = FLOOD + 'HighLikelihood'
FLOOD_IMPACT = FLOOD + 'Impact'
FLOOD_INDUSTRIALAREA = FLOOD + 'IndustrialArea'
FLOOD_INFRASTRUCTURECOMPONENT = FLOOD + 'InfrastructureComponent'      
FLOOD_LIKELIHOOD = FLOOD + 'Likelihood'
FLOOD_LOCATION = FLOOD + 'Location'
#FLOOD_LOWLIKELIHOOD = FLOOD + 'LowLikelihood'
#FLOOD_MEDIUMLIKELIHOOD = FLOOD + 'MediumLikelihood'
#FLOOD_MINIMALIMPACT = FLOOD + 'MinimalImpact'
#FLOOD_MINORIMPACT = FLOOD + 'MinorImpact'
FLOOD_MOBILITYNETWORK = FLOOD + 'MobilityNetwork'
FLOOD_NETWORKINFRASTRUCTURE = FLOOD + 'NetworkInfrastructure'
FLOOD_POPULATION = FLOOD + 'Population'
FLOOD_POTENTIALIMPACT = FLOOD + 'PotentialImpact'
FLOOD_PREDICTS = FLOOD + 'predicts'
FLOOD_PROVISIONINGNETWORK = FLOOD + 'ProvisioningNetwork'
FLOOD_RESIDENTIALAREA = FLOOD + 'ResidentialArea'
FLOOD_RESULTSIN = FLOOD + 'resultsIn'
FLOOD_RISKLEVEL = FLOOD + 'RiskLevel'
FLOOD_RIVERWATER = FLOOD + 'RiverWater'
#FLOOD_SEVEREFLOODWARNING = FLOOD + 'SevereFloodWarning'
#FLOOD_SEVEREIMPACT = FLOOD + 'SevereImpact'
FLOOD_SEVERITY = FLOOD + 'Severity'
#FLOOD_SIGNIFICANTIMPACT = FLOOD + 'SignificantImpact'
FLOOD_SURFACEWATER = FLOOD + 'SurfaceWater'
FLOOD_VEHICLE = FLOOD + 'Vehicle'
#FLOOD_VERYLOWLIKELIHOOD = FLOOD + 'VeryLowLikelihood'
#FLOOD_WARNINGNOLONGERINFORCE = FLOOD + 'WarningNoLongerInForce'
FLOOD_WARNSABOUT = FLOOD + 'warnsAbout'
FLOOD_WATERVELOCITY = FLOOD + 'WaterVelocity'
# ABox
FLOOD_VERYLOWLIKELIHOOD = FLOOD + 'VeryLowLikelihood_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_LOWLIKELIHOOD = FLOOD + 'LowLikelihood_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_MEDIUMLIKELIHOOD = FLOOD + 'MediumLikelihood_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_HIGHLIKELIHOOD = FLOOD + 'HighLikelihood_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_SEVEREIMPACT = FLOOD + 'SevereImpact_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_SIGNIFICANTIMPACT = FLOOD + 'SignificantImpact_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_MINORIMPACT = FLOOD + 'MinorImpact_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_MINIMALIMPACT = FLOOD + 'MinimalImpact_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_SEVEREFLOODWARNING = FLOOD + 'SevereFloodWarning_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_FLOODWARNING = FLOOD + 'FloodWarning_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_FLOODALERT = FLOOD + 'FloodAlert_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'
FLOOD_WARNINGNOLONGERINFORCE = FLOOD + 'InactiveFloodWarning_ca5e5580-7ab8-4e1c-9087-8cbc893d5c5b'

# OntoTimeSeries
TS_HASRDB = TS + 'hasRDB'
TS_HASTIMESERIES = TS + 'hasTimeSeries'
TS_HASTIMEUNIT = TS + 'hasTimeUnit'
TS_TIMESERIES = TS + 'TimeSeries'

# Time ontology
TIME_HASBEGINNING = TIME + 'hasBeginning'
TIME_HASEND = TIME + 'hasEnd'
TIME_HASXSDDURATION = TIME + 'hasXSDDuration'
TIME_INSTANT = TIME + 'Instant'
TIME_INTERVAL = TIME + 'Interval'
TIME_INXSDDATETIMESTAMP = TIME + 'inXSDDateTimeStamp'

# Ontology of units of measure
OM_AMOUNTOFMONEY = OM + 'AmountOfMoney'
OM_AREA = OM + 'Area'
OM_DEPTH = OM + 'Depth'
OM_HASNUMERICALVALUE = OM + 'hasNumericalValue'
OM_HASUNIT = OM + 'hasUnit'
OM_HASVALUE = OM + 'hasValue'
OM_MEASURE = OM + 'Measure'
OM_QUANTITY = OM + 'Quantity'
OM_SYMBOL = OM + 'symbol'
OM_UNIT = OM + 'Unit'
OM_VELOCITY = OM + 'Velocity'

# RT (Environment Agency)
RT_CURRENTWARNING = RT + 'currentWarning'
RT_FLOODALERTAREA = RT + 'FloodAlertArea'
RT_FLOODALERTORWARNING = RT + 'FloodAlertOrWarning'
RT_FLOODAREA = RT + 'FloodArea'
RT_FLOODWARNINGAREA = RT + 'FloodWarningArea'
RT_MESSAGE = RT + 'message'
RT_TIMEMESSAGECHANGED = RT + 'timeMessageChanged'
RT_TIMERAISED = RT + 'timeRaised'
RT_TIMESEVERITYCHANGED = RT + 'timeSeverityChanged'

# ENVO
ENVO_WATER_BODY = ENVO + 'ENVO_00000063'
ENVO_CANAL = ENVO + 'ENVO_00000014'
ENVO_SEA = ENVO + 'ENVO_00000016'
ENVO_LAKE = ENVO + 'ENVO_00000020'
ENVO_RIVER = ENVO + 'ENVO_00000022'
ENVO_FLOOD = ENVO + 'ENVO_01000710'
ENVO_COASTAL_FLOOD = ENVO + 'ENVO_01000711'
ENVO_RIVERINE_FLOOD = ENVO + 'ENVO_01000712'
ENVO_FLASH_FLOOD = ENVO + 'ENVO_01000713'
ENVO_FORMED_AS_RESULT_OF = ENVO + 'RO_0002354'
ENVO_COASTAL_FLOODING = ENVO + 'ENVO_01000707'
ENVO_RIVERINE_FLOODING = ENVO + 'ENVO_01000708'
ENVO_FLASH_FLOODING = ENVO + 'ENVO_01000709'
ENVO_AREAL_FLOODING = ENVO + 'ENVO_01000717'
ENVO_URBAN_FLOODING = ENVO + 'ENVO_01000718'
ENVO_FLOODING = ENVO + 'ENVO_02500002'

# SOPH, SOPHHY
SOPH_EVENT = SOPH + 'Event'
SOPHHY_FLOOD = SOPHHY + 'Flood'

# Data types
RDF_TYPE = RDF + 'type'
RDFS_COMMENT = RDFS + 'comment'
RDFS_LABEL = RDFS + 'label'
XSD_STRING = XSD + 'string'
XSD_FLOAT = XSD + 'float'
XSD_DATETIME = XSD + 'dateTime'

# GeoSPARQL
GEO_FEATURE = GEO + 'Feature'
GEO_HAS_GEOMETRY = GEO + 'hasGeometry'
GEO_ASWKT = GEO + 'asWKT'

# OWL
OWL_VERSION = OWL + 'versionInfo'
OWL_SAMEAS = OWL + 'sameAs'


# OM / UOM unit symbols
OM_GBP = OM + 'poundSterling'
# NOTE: There are reported issues with encoding of special characters, i.e. Blazegraph
#       claiming to use utf-8 encoding while actually using iso-8859-1
#       --> PoundSterling displayed wrongly in GUI but correctly retrieved within code
# Details: https://github.com/blazegraph/database/issues/224
GBP_SYMBOL = '£'