__doc__ = """
This module defines all the ominp json file keys.
"""

# OMINP_JSON_KEYS
# -------------------------
MOPS_MOLECULAR_WEIGHT = "Mops_Molecular_Weight"
MOPS_POLYHEDRAL_SHAPE = "Mops_Polyhedral_Shape"
MOPS_POLYHEDRAL_SHAPE_SYMBOL = "Mops_Polyhedral_Shape_Symbol"
MOPS_SYMMETRY_POINT_GROUP = "Mops_Symmetry_Point_Group"
MOPS_CHARGE = "Mops_Charge"
MOPS_FORMULA = "Mops_Formula"
MOPS_LABEL = "Mops_Label"
MOPS_CAVITY_VOLUME = "Mops_Cavity_Volume"
MOPS_CCDC_NUMBER = "Mops_CCDC_Number"
MOPS_REFERENCE_DOI = "Mops_Reference_DOI"
MOPS_XYZ_COORDINATES_FILE = "Mops_XYZ_Coordinates_File"
MOPS_CHEMICAL_BUILDING_UNITS = "Mops_Chemical_Building_Units"
SPECIES_IRI = "Species_IRI"
CBU_FORMULA = "CBU_Formula"
CBU_BINDING_SITE = "CBU_Binding_Site"
CBU_BINDING_SITE_LABEL = "CBU_Binding_Site_Label"
CBU_BINDING_SITE_COORD_NUMBER = "CBU_Binding_Site_Coord_Number"
CBU_CORE_LABEL = "CBU_Core_Label"
CBU_CORE_SUBSTITUENT_LABEL = "CBU_Core_Substituent_Label"
CBU_SPACER_LABEL = "CBU_Spacer_Label"
CBU_SPACER_SUBSTITUENT_LABEL = "CBU_Spacer_Substituent_Label"
CBU_BINDING_DIRECTION = "CBU_Binding_Direction"
GBU_PLANARITY = "GBU_Planarity"
GBU_MODULARITY = "GBU_Modularity"
GBU_NUMBER = "GBU_Number"


OMINP_JSON_KEYS = [
    MOPS_MOLECULAR_WEIGHT,
    MOPS_POLYHEDRAL_SHAPE,
    MOPS_POLYHEDRAL_SHAPE_SYMBOL,
    MOPS_SYMMETRY_POINT_GROUP,
    MOPS_CHARGE,
    MOPS_FORMULA,
    MOPS_LABEL,
    MOPS_CAVITY_VOLUME,
    MOPS_CCDC_NUMBER,
    MOPS_REFERENCE_DOI,
    MOPS_XYZ_COORDINATES_FILE,
    MOPS_CHEMICAL_BUILDING_UNITS,
    SPECIES_IRI,
    CBU_FORMULA,
    CBU_BINDING_SITE,
    CBU_BINDING_SITE_LABEL,
    CBU_BINDING_SITE_COORD_NUMBER,
    CBU_CORE_LABEL,
    CBU_CORE_SUBSTITUENT_LABEL,
    CBU_SPACER_LABEL,
    CBU_SPACER_SUBSTITUENT_LABEL,
    CBU_BINDING_DIRECTION,
    GBU_PLANARITY,
    GBU_MODULARITY,
    GBU_NUMBER,
]
