# First import the common iris from pyderivationagent
from pyderivationagent.data_model.iris import *

# Then, define specific concepts and properties IRIs for your project here

DERIVATION_AGENT_PYTHON_EXAMPLE_BASE_URL = 'http://www.example.org/derivationagentpythonexample#'

DERIVATION_AGENT_PYTHON_EXAMPLE_MINVALUE = DERIVATION_AGENT_PYTHON_EXAMPLE_BASE_URL + 'MinValue'
DERIVATION_AGENT_PYTHON_EXAMPLE_MAXVALUE = DERIVATION_AGENT_PYTHON_EXAMPLE_BASE_URL + 'MaxValue'
DERIVATION_AGENT_PYTHON_EXAMPLE_DIFFERENCE = DERIVATION_AGENT_PYTHON_EXAMPLE_BASE_URL + 'Difference'
DERIVATION_AGENT_PYTHON_EXAMPLE_HASVALUE = DERIVATION_AGENT_PYTHON_EXAMPLE_BASE_URL + 'hasValue'
DERIVATION_AGENT_PYTHON_EXAMPLE_VALUE = DERIVATION_AGENT_PYTHON_EXAMPLE_BASE_URL + 'Value'
DERIVATION_AGENT_PYTHON_EXAMPLE_NUMVAL = DERIVATION_AGENT_PYTHON_EXAMPLE_BASE_URL + 'numVal'
