from matchers.MeronymRematcher import *
from matchers.BOWMatcher import  *
from matchers.domainMatcher import *
from matchers.StringMatcher import *
from matchers.valueMatcher import *
from matchers.elementMatcher import *
from matchers.instanceStringMatcher import *
from matchers.instanceBOWMatcher import *
from matchers.GeoAttrFinder import *
from matchers.Penalizer import *
