###--- Supported observation and forecast types by OntoEMS ---###
WATER_LEVEL = 'WaterLevel'
RAINFALL = 'Rainfall'
WATER_FLOW = 'WaterFlow'
AIR_TEMPERATURE = 'AirTemperature'
WIND_SPEED = 'WindSpeed'
WIND_GUST = 'WindGust'
WIND_DIRECTION = 'WindDirection'
FEELS_LIKE_TEMPERATURE = 'FeelsLikeTemperature'
DEW_POINT = 'DewPoint'
ATMOSPHERIC_PRESSURE = 'AtmosphericPressure'
RELATIVE_HUMIDITY = 'RelativeHumidity'
UV_INDEX = 'UVIndex'
VISIBILITY = 'Visibility'
PRECIPITATION_PROBABILITY = 'PrecipitationProbability'
AIR_POLLUTANT_CONCENTRATION = 'AirPollutantConcentration'
DIRECT_HORIZONTAL_IRRADIANCE = 'DirectHorizontalIrradiance'
DIFFUSE_HORIZONTAL_IRRADIANCE = 'DiffuseHorizontalIrradiance'
GLOBAL_HORIZONTAL_IRRADIANCE = 'GlobalHorizontalIrradiance'

# OM SYMBOLS for observation types
DEG_C = '°C'
HEC_PA = 'hPa'
PERCENT = '%'
METRE = 'm'
MI_PH = 'mi/h'
DEG = '°'