prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix ems: <https://www.theworldavatar.com/kg/ontoems/>

SELECT ?label ?value ?unit
WHERE {
  { BIND ("Type" AS ?label )
    <STATION_IRI> rdf:type ?value_ini .
    BIND (replace(str(?value_ini), str(ems:), '') as ?value)
  } UNION { 
    BIND ("Name" AS ?label )
    <STATION_IRI> rdfs:label ?value .
  } UNION { 
    BIND ("Data source" AS ?label )
    <STATION_IRI> ems:dataSource ?value .
  } UNION { 
    BIND ("Identifier" AS ?label )
    <STATION_IRI> ems:hasIdentifier ?value .
  } UNION { 
    BIND ("Elevation" AS ?label )
    BIND ("m" AS ?unit )
    <STATION_IRI> ems:hasObservationElevation ?value .
  }
}