// These are two example HTTP requests to retrieve data about Met Office stations and create
// the respective output files required by the Digital Twin Visualisation Framework

// The GET request expects all individual query parameter to be provided in a single nested 
// JSON object with key 'query' (to follow a convention from the JPS_BASE_LIB)
// Required query parameters:
//    outDir ... output directory for DTVF files
// Optional query parameters:
//    daysBack ... Number of previous days for which to retrieve data (default: last 14 days)
//    observationTypes ... List of observation types for which to retrieve data (default: all)
//                         (i.e. observation types as defined by OntoEMS, either as full IRIs or shorthands)
//    splitObsFcs ... Boolean flag whether to create joint or separate file sets for observations
//                    and forecasts (default: single file for observations and forecasts)
//    circleCenter ... Circle center as "latitude#longitude" in EPSG:4326 for geospatial search (via PostGIS)
//                     (default: No geospatial search, retrieve all data)
//    circleRadius ... Circle radius around center in km (default: None)
//                     (circleCenter and circleRadius are only considered to retrieve data within
//                      a particular area of interest if both are provided)


// Retrieve all available stations and time series data as of 14 days back
// Output directory path depends on whether agent is deployed ...
//    ... locally: "<path to Agents folder>/MetOfficeAgent/output"
//    ... in Docker container: "/app/output"
GET http://165.232.172.16:5000/api/metofficeagent/retrieve/all
Content-Type: application/json

{ "query": {
      "outDir": "/app/output",
      "splitObsFcs": true,
      "daysBack": "14"
    }
}


// Retrieve only selected stations and time series data as of 14 days back
// Please NOTE that circleCenter and circleRadius require geospatially enabled Blazegraph namespace

# GET http://165.232.172.16:5000/api/metofficeagent/retrieve/all
# Content-Type: application/json

# { "query": {
#       "outDir": "/app/output",
#       "daysBack": 7,
#       "observationTypes": ["AirTemperature", "<https://www.theworldavatar.com/kg/ontoems/WindGust>"],
#       "splitObsFcs": true,
#       "circleCenter": "52.75#0.4",
#       "circleRadius": 100
#     }
# }
