PREFIX ems: <https://www.theworldavatar.com/kg/ontoems/>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>

SELECT * 
WHERE	{
			{
				[IRI]
                <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?Latitude ;
				<http://www.w3.org/2003/01/geo/wgs84_pos#long> ?Longitude ;
				<http://environment.data.gov.uk/flood-monitoring/def/core/stationReference> ?Station_Reference .
			}
			{
				
				OPTIONAL { [IRI] <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/easting> ?Easting . }
				OPTIONAL { [IRI] <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/northing> ?Northing . }
				OPTIONAL { [IRI] <http://environment.data.gov.uk/flood-monitoring/def/core/gridReference> ?Grid_Reference . }
                OPTIONAL { [IRI] <https://www.theworldavatar.com/kg/ontoems/dataSource> ?Data_Source . }
                OPTIONAL { [IRI] <https://www.theworldavatar.com/kg/ontoems/hasObservationLocation> ?Observation_Location . }
    			OPTIONAL { [IRI] <http://environment.data.gov.uk/flood-monitoring/def/core/dateOpened> ?Date_Opened . }
				OPTIONAL { [IRI] <http://www.w3.org/2000/01/rdf-schema#label> ?Station_Name . }
				OPTIONAL { [IRI] ems:reports/om:hasValue ?Measurement . }
			}
			OPTIONAL {
				?Measurement
                <http://environment.data.gov.uk/flood-monitoring/def/core/parameterName> ?Measurement_Parameter ;
				<http://environment.data.gov.uk/flood-monitoring/def/core/qualifier> ?Measurement_Qualifier ;
				<http://environment.data.gov.uk/flood-monitoring/def/core/unitName> ?Measurement_Unit .
				FILTER ( !BOUND(?Measurement) )
			}
		}