#!/bin/bash
#------------------------------------------------------------------------------#
#                    Script to run EPISODE CityChem On CSD3                    #
#                    Author: Kok Foong Lee (kflee@cmclinnovations.com)         #
#------------------------------------------------------------------------------#
mv *.zip input.zip
unzip -o input.zip -d input
inputDir=$PWD

#create directory to store inputs for EPISODE
#they will be generated by the preprocessors
mkdir INPUT OUTPUT
cd INPUT
mkdir emis mcwind other 

#weather preprocessor: this will create input files in INPUT/mcwind
cd ${inputDir}/input
~/citychem-1.3/preproc/mcwind/bin/MCWIND.exe

# kinetics is using LD_LIBRARY_PATH for the lmx wrapper
LD_LIBRARY_PATH=${HOME}/netcdf4/lib

# this will generate files for point source emissions
~/citychem-1.3/preproc/uect2.3/bin/uect.exe

# replace the string PSE to LSE in the input file
sed -i 's/'PSE'/'LSE'/g' cctapm_meta.inp

# create files for line emissions
~/citychem-1.3/preproc/uect2.3/bin/uect.exe

# receptor (Kang's code)
gfortran ~/citychem-1.3/receptor_raster_kang/receptor_raster.f90
./a.out

# launch main program - citychem
~/citychem-1.3/bin/citychem.exe citychem_restart.txt

# zip output files
cd ${inputDir}/OUTPUT
zip -r ${inputDir}/output.zip *.*

echo "Simulation Completed."
