// Example HTTP request to instantiate latest EPC building data for all instantiated UPRNs (and postcodes)
// retrieving data from specified EPC API

// epc_endpoint: EPC endpoint from which to retrieve data 
//               ['domestic', 'non-domestic', 'display']
// ocgml_endpoint: Available SPARQL endpoint containing instantiated buildings in OntoCityGML
//                 (the agent only instantiates EPC data for buildings instantiated in OntoCityGml)
//                 --> OPTIONAL: if not provided, default namespace from environment variables will be used

POST http://165.232.172.16:5005/epcagent/instantiate/certificates/all
Content-Type: application/json

# # Domestic API
# { "query": {
#       "epc_endpoint": "domestic",
#       "ocgml_endpoint": "http://165.232.172.16:3838/blazegraph/namespace/ocgml/sparql"
#     }
# }

# # Non-domestic API
# { "query": {
#       "epc_endpoint": "non-domestic",
#       "ocgml_endpoint": "http://165.232.172.16:3838/blazegraph/namespace/ocgml/sparql"
#     }
# }

# Display API
{ "query": {
      "epc_endpoint": "display",
      "ocgml_endpoint": "http://165.232.172.16:3838/blazegraph/namespace/ocgml/sparql"
    }
}
