// Example HTTP request to instantiate EPC building data for given certificate 

// lmk_key: Individual lodgement identifier of particular EPC (see: https://epc.opendatacommunities.org/docs/api/domestic#domestic-cert)
// epc_endpoint: EPC endpoint from which to retrieve data 
//               ['domestic', 'non-domestic', 'display']
// ocgml_endpoint: Available SPARQL endpoint containing instantiated buildings in OntoCityGML
//                 (the agent only instantiates EPC data for buildings instantiated in OntoCityGml)
//                 --> OPTIONAL: if not provided, default namespace from environment variables will be used

// Non-domestic query
// { "query": {
//      "lmk_key": "54715380002011092111465010400280",
//      "epc_endpoint": "non-domestic",
//      "ocgml_endpoint": "http://165.232.172.16:3838/blazegraph/namespace/ocgml/sparql"
//   }
//}

POST http://165.232.172.16:5001/epcagent/instantiate/certificates/single
Content-Type: application/json

{ "query": {
      "lmk_key": "260808730062009040611251270078171",
      "epc_endpoint": "domestic",
      "ocgml_endpoint": "http://165.232.172.16:3838/blazegraph/namespace/ocgml/sparql"
    }
}
