prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix om:   <http://www.ontology-of-units-of-measure.org/resource/om-2/>
prefix ems:  <https://www.theworldavatar.com/kg/ontoems/>
prefix rt:   <http://environment.data.gov.uk/flood-monitoring/def/core/>
prefix owl:  <http://www.w3.org/2002/07/owl#>



SELECT ?Measurement ?Name ?Unit
WHERE { 

  {
  
  [IRI] <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.theworldavatar.com/kg/ontoems/ReportingStation> ;
            ems:reports ?quantity.
       ?quantity rdf:type <https://www.theworldavatar.com/kg/ontoems/NitrogenOxidesConcentration>.
       ?quantity om:hasValue ?Measurement.
       ?Measurement om:hasUnit <http://www.ontology-of-units-of-measure.org/resource/om-2/microgramPerCubicmetre>;
                <https://www.theworldavatar.com/kg/ontotimeseries/hasTimeSeries> ?tsIRI.
        BIND("NOx Concentration" AS ?Name).
        BIND("micro-gram/m3" AS ?Unit).
       
      }
  UNION {

     [IRI] <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.theworldavatar.com/kg/ontoems/ReportingStation> ;
            ems:reports ?quantity.
       ?quantity rdf:type <https://www.theworldavatar.com/kg/ontoems/PM10Concentration>.
       ?quantity om:hasValue ?Measurement.
       ?Measurement om:hasUnit <http://www.ontology-of-units-of-measure.org/resource/om-2/microgramPerCubicmetre>;
                <https://www.theworldavatar.com/kg/ontotimeseries/hasTimeSeries> ?tsIRI.
        BIND("PM10 Concentration" AS ?Name).
        BIND("micro-gram/m3" AS ?Unit).

  }

  UNION {

     [IRI] <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.theworldavatar.com/kg/ontoems/ReportingStation> ;
            ems:reports ?quantity.
       ?quantity rdf:type <https://www.theworldavatar.com/kg/ontoems/PM2.5Concentration>.
       ?quantity om:hasValue ?Measurement.
       ?Measurement om:hasUnit <http://www.ontology-of-units-of-measure.org/resource/om-2/microgramPerCubicmetre>;
                <https://www.theworldavatar.com/kg/ontotimeseries/hasTimeSeries> ?tsIRI.
        BIND("PM2.5 Concentration" AS ?Name).
        BIND("micro-gram/m3" AS ?Unit).

  }

}