POST http://localhost:3838/buildingidentificationagent/postgis
content-type: application/json

{
    "maxDistance": "50",
    "table": "acraregisteredcompanyaddress",
    "column": "wkb_geometry",
    "oneToMany": "false"
}