package uk.ac.cam.cares.jps.sensor.source.database.model.entity;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents unsent sensor data that needs to be stored locally when network connectivity is unavailable.
 * This data can be retrieved and sent when the network is restored.
 * The data is stored in the "unsent_data" table in the database.
 */
@Entity(tableName = "unsent_data")
public class UnsentData {

    /**
     * The unique ID of the unsent data record.
     * This field is auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    public int id;

    /**
     * The serialized sensor data in a JSON string format.
     */
    @ColumnInfo(name = "data")
    public String data;  // serialized map of data using a string --> method is network class

    /**
     * Id associated with the device in use.
     */
    @ColumnInfo(name = "device_id")
    public String deviceId;

    /**
     * Time of the data being processed.
     */
    @ColumnInfo(name = "timestamp")
    public long timestamp;

    /**
     * Hash value of data for efficient comparisons.
     */
    @ColumnInfo(name = "dataHash")
    public String dataHash;
}
