{
 "title": "Overview",
 "time": { "from": "1927-01-01T00:00:00.000Z", "to": "2023-01-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Number of sites",
   "type": "stat",
   "description": "Total number of sites.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ogc_fid) FROM dukes_2023 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Sites by type",
   "type": "barchart",
   "description": "UK power generation sites aggregated by type.",
   "gridPos": { "h": 8, "w": 14, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Site Type\", COUNT(\"Site Type\") AS \"Sites\" FROM dukes_2023 GROUP BY \"Site Type\" ORDER BY COUNT(\"Site Type\") DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Combined Heat & Power",
   "type": "piechart",
   "description": "Breakdown of sites that offer Combined Heat & Power.",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(\"Combined Heat and Power\" AS VARCHAR(10)), COUNT(\"Combined Heat and Power\") FROM dukes_2023 GROUP BY \"Combined Heat and Power\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Grid Connection Type",
   "type": "piechart",
   "description": "Breakdown of Grid Connection Types offered by sites.",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Grid Connection Type\", COUNT(\"Grid Connection Type\") FROM dukes_2023 WHERE \"Grid Connection Type\" IS NOT NULL GROUP BY \"Grid Connection Type\""
    }
   ]
  },
  {
   "title": "Installed Capacity",
   "type": "barchart",
   "description": "Minimum and maximum Installed Capacity (MW) grouped by Site Type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"Site Type\", MIN(\"Installed Capacity (MW)\") AS \"Minimum\", MAX(\"Installed Capacity (MW)\") AS \"Maximum\" FROM dukes_2023 GROUP BY \"Site Type\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Top 10 Companies",
   "type": "barchart",
   "description": "The top 10 companies with the most sites.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"Company Name\", COUNT(\"Company Name\") AS \"Sites\" FROM dukes_2023 GROUP BY \"Company Name\" ORDER BY COUNT(\"Company Name\") DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "Sites commissioned by year",
   "type": "timeseries",
   "description": "A breakdown of the number of sites commissioned by year.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT CAST(CONCAT(CAST(\"Year Commissioned\" as VARCHAR(4)), '0101') AS date), COUNT(\"Year Commissioned\") FROM dukes_2023 GROUP BY \"Year Commissioned\" ORDER BY \"Year Commissioned\" ASC "
    }
   ]
  }
 ]
}