DB_USER='postgres'
DB_PASSWORD='postgres'
DB_URL='jdbc:postgresql://localhost:7432/postgres'
QUERY_ENDPOINT='http://localhost:27149/blazegraph/namespace/kb/sparql'
UPDATE_ENDPOINT='http://localhost:27149/blazegraph/namespace/kb/sparql'
ONTOP_URL=''
