prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix om:  <http://www.ontology-of-units-of-measure.org/resource/om-2/>
prefix ems: <https://www.theworldavatar.com/kg/ontoems/>

SELECT ?Measurement ?Name ?Unit
WHERE {
  {
  # Observations/Measurements
  [IRI] ems:reports/om:hasValue ?Measurement . 
  #?Measurement ^om:hasValue/rdf:type <https://www.theworldavatar.com/kg/ontoems/RelativeHumidity> . 
  ?Measurement ^om:hasValue/rdf:type ?type ; 
               om:hasUnit/om:symbol ?Unit .                
  BIND (concat(replace(str(?type), str(ems:), ''), ' observation') as ?Name)               
  # Forecasts
  } UNION {
  [IRI] ems:reports/ems:hasForecastedValue ?Measurement . 
  #?Measurement ^om:hasValue/rdf:type <https://www.theworldavatar.com/kg/ontoems/RelativeHumidity> . 
  ?Measurement ^ems:hasForecastedValue/rdf:type ?type ; 
               om:hasUnit/om:symbol ?Unit .                
  BIND (concat(replace(str(?type), str(ems:), ''), ' forecast') as ?Name)    
  }
}