PREFIX obe: <https://www.theworldavatar.com/kg/ontobuiltenv/>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX iso: <https://www.theworldavatar.com/kg/ontoisochrone/>

SELECT DISTINCT ?label ?value ?unit
WHERE {
SERVICE [ONTOP] {
SELECT DISTINCT ?label ?value ?unit
WHERE {
            {
                [IRI] iso:assumesTransportMode ?transportmode_iri.
                ?transportmode_iri a ?TransportMode.
              
                BIND ("Transport Mode" AS ?label )
                BIND (replace(str(?TransportMode), str(iso:), '') AS ?value)
            }
          UNION
                      {
                [IRI] iso:originatesFrom ?poi_iri.
                ?poi_iri a ?poi_type.
              
                BIND ("Isochrone Origins" AS ?label )
                BIND (replace(str(?poi_type), str(obe:), '') AS ?value)
            }
          UNION
                      
          {
                [IRI] iso:hasTimeThreshold ?timeThreshold.
           
              
                BIND ("Time Threshold" AS ?label )
                BIND (?timeThreshold AS ?value)
                BIND ("minutes" AS ?unit)
            }
          UNION
                    
            {
                [IRI] iso:hasRoadCondition ?roadcondition_iri.
                ?roadcondition_iri a ?RoadCondition.
              
                BIND ("Road Condition" AS ?label )
                BIND (replace(str(?RoadCondition), str(iso:), '') AS ?value)
            }
          UNION
           {
                [IRI] iso:hasTotalPopulation ?totalpopulation.
              
                BIND ("Total Population" AS ?label )
                BIND (?totalpopulation AS ?value)
            }
          UNION
          {
            [IRI] iso:hasMenPopulation ?population_men
            BIND ("Male Population" AS ?label)
            BIND (?population_men AS ?value)
          }
          UNION
          {
            [IRI] iso:hasWomenPopulation ?population_female
            BIND ("Female Population" AS ?label)
            BIND (?population_female AS ?value)
          }
                    UNION
          {
            [IRI] iso:hasWomenofReproductiveAge ?repro_population_female
            BIND ("Women of Reproductive Age Population" AS ?label)
            BIND (?repro_population_female AS ?value)
          }
                    UNION
          {
            [IRI] iso:hasChildrenPopulation ?population_child
            BIND ("Children Population" AS ?label)
            BIND (?population_child AS ?value)
          }
                              UNION
          {
            [IRI] iso:hasYouthPopulation ?population_youth
            BIND ("Youth Population" AS ?label)
            BIND (?population_youth AS ?value)
          }
                                        UNION
          {
            [IRI] iso:hasElderlyPopulation ?population_elderly
            BIND ("Elderly Population" AS ?label)
            BIND (?population_elderly AS ?value)
          }
    }
}
}