package uk.ac.cam.cares.jps.agent.dashboard.json;

import uk.ac.cam.cares.jps.agent.dashboard.json.panel.PanelModel;
import uk.ac.cam.cares.jps.agent.dashboard.json.templating.TemplatingModel;

import java.util.List;
import java.util.Map;

/**
 * A Java representation of a JSON-like model that encapsulates and enforces information about syntax specific to Grafana dashboard.
 *
 * @author qhouyee
 */
public class GrafanaModel {
    private String dashboardId;
    private String dashboardUid;
    private boolean overwrite;
    private final String dashboardTitle;
    private final String dashboardRefreshRate;
    private final String comment;
    private final String templatingSyntax;
    private final String panelSyntax;

    /**
     * Constructor that provides default settings to set up a new dashboard. The default refresh rate is 20seconds.
     * New dashboard ID and UID will be generated in this process.
     *
     * @param title                 The title of the dashboard.
     * @param databaseConnectionMap A map linking each database to its connection ID.
     * @param timeSeries            A map of all assets and rooms mapped to their time series.
     */
    public GrafanaModel(String title, Map<String, String> databaseConnectionMap, Map<String, Map<String, List<String[]>>> timeSeries) {
        // Grafana has enforced a default comment for the first version, which cannot be changed
        this(title, null, "null", "20s", "Initialised dashboard", databaseConnectionMap, timeSeries);
    }

    /**
     * Basic Constructor that provides customised settings.
     *
     * @param title                 The title of the dashboard.
     * @param dashboardId           The dashboard ID generated by Grafana. For creating new dashboards, ONLY pass null value. For updating an existing dashboard, users MUST pass the corresponding ID as an Integer.
     * @param dashboardUid          Optional unique identifier when creating a dashboard. Pass null as a String to generate a new uid.
     * @param refreshRate           The refresh rate of the real-time dashboard. Sample values: 5s, 1m, 1h, 1d.
     * @param comment               A comment for version control purposes.
     * @param databaseConnectionMap A map linking each database to its connection ID.
     * @param timeSeries            A map of all assets and rooms mapped to their time series.
     */
    public GrafanaModel(String title, Integer dashboardId, String dashboardUid, String refreshRate, String comment, Map<String, String> databaseConnectionMap, Map<String, Map<String, List<String[]>>> timeSeries) {
        this.dashboardTitle = title;
        // If setting up a new dashboard, please pass null as a parameter to generate the ID. If updating an existing dashboard, please pass the original id
        this.dashboardId = dashboardId == null ? "null" : dashboardId.toString();
        // If setting a customised dashboard UID, it must be enclosed with double quotes and a backslash eg \"
        this.dashboardUid = dashboardUid.equals("null") ? dashboardUid : "\"" + dashboardUid + "\"";
        this.overwrite = false;
        this.dashboardRefreshRate = refreshRate;
        this.comment = comment;
        // Construct the templating syntax from the model
        this.templatingSyntax = new TemplatingModel(databaseConnectionMap, timeSeries).construct();
        this.panelSyntax = new PanelModel(databaseConnectionMap, timeSeries).construct();
    }

    /**
     * Set the id configuration if the dashboard already exists.
     *
     * @param id  The id of the dashboard.
     * @param uid The uid of the dashboard generated by Grafana.
     */
    protected void setExistingIds(int id, String uid) {
        this.dashboardId = String.valueOf(id);
        this.dashboardUid = "\"" + uid + "\"";
        this.overwrite = true;
    }

    /**
     * Construct the JSON model as a String.
     *
     * @return The JSON model syntax as a String.
     */
    protected String construct() {
        StringBuilder builder = new StringBuilder();
        builder.append("{\"dashboard\": {")
                // generate new id and uid using null
                .append("\"id\":").append(this.dashboardId).append(",")
                .append("\"uid\":").append(this.dashboardUid).append(",")
                // The dashboard title
                .append("\"title\": \"").append(this.dashboardTitle).append("\",")
                // Templating
                .append("\"templating\": ").append(this.templatingSyntax).append(",")
                // Panel
                .append("\"panels\": [").append(this.panelSyntax).append("],")
                // Disable any editing by non-admin users
                .append("\"editable\": false,")
                .append("\"timezone\": \"browser\",")
                // Default view - time frame
                .append("\"time\": {\"from\": \"now-3h\", \"to\": \"now\"},")
                .append("\"refresh\": \"").append(this.dashboardRefreshRate).append("\"")
                .append("},")
                // Comments for each update/ version
                .append("\"message\": \"").append(this.comment).append("\",")
                .append("\"overwrite\": ").append(this.overwrite).append("}");
        return builder.toString();
    }
}
