###--- Supported observation types by OntoEMS (relevant for UK Air) ---###
AIR_TEMPERATURE = 'AirTemperature'
WIND_SPEED = 'WindSpeed'
WIND_GUST = 'WindGust'
WIND_DIRECTION = 'WindDirection'
FEELS_LIKE_TEMPERATURE = 'FeelsLikeTemperature'
DEW_POINT = 'DewPoint'
ATMOSPHERIC_PRESSURE = 'AtmosphericPressure'
RELATIVE_HUMIDITY = 'RelativeHumidity'
AIR_POLLUTANT_CONCENTRATION = 'AirPollutantConcentration'
SO2_CONCENTRATION = 'SulfurDioxideConcentration'
NOX_CONCENTRATION = 'NitrogenOxidesConcentration'
NO_CONCENTRATION = 'NitrogenMonoxideConcentration'
NO2_CONCENTRATION = 'NitrogenDioxideConcentration'
PM_CONCENTRATION = 'ParticulateMatterConcentration'
PM2_5_CONCENTRATION = 'PM2.5Concentration'
PM10_CONCENTRATION = 'PM10Concentration'
O3_CONCENTRATION = 'OzoneConcentration'

# OM SYMBOLS for observation types
# original OM symbol for °C: '&#x00B0;C'
# original OM symbol for °: '&#x00B0;'
DEG_C = '°C'
HEC_PA = 'hPa'
PERCENT = '%'
MI_PH = 'mi/h'
DEG = '°'
MILLIG_M3 = 'mg/m3'
MICROG_M3 = 'µg/m3'
NANOG_M3 = 'ng/m3'