PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ser: <https://theworldavatar.io/kg/service#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?class
WHERE {
    {
        SELECT DISTINCT ?all_endpoints
        WHERE {
            {
                VALUES ?all_endpoints { [ENDPOINTS-ALL] }
            }
            UNION
            {
                VALUES ?serviceType { ser:Ontop }
                ?service a ?serviceType ;
                   dcat:endpointURL ?all_endpoints .
            }
        }
    }
    VALUES ?kg_endpoints { [ENDPOINTS-BLAZEGRAPH] }
    SERVICE ?all_endpoints {
        [IRI] a ?type .
    }
    SERVICE ?kg_endpoints {
        ?type rdfs:subClassOf* ?class .
    }
    FILTER (!isBlank(?class))
}