PREFIX books: <http://meraka/moss/exampleBooks.owl#>
SELECT DISTINCT ?book
WHERE { 
?book a <http://meraka/moss/exampleBooks.owl#AudioBook> .
?book a <http://meraka/moss/exampleBooks.owl#E-Book> .  
}