package uk.ac.cam.cares.jps.agent.flood;

/**
 * Configs set via environment variables
 */
public class EnvConfig {
	// set true to download datum information for each station, only need to do once to download the file
	public static final boolean DOWNLOAD_DATUM = Boolean.parseBoolean(System.getenv("DOWNLOAD_DATUM"));
	public static final String DATUM_FILE = System.getenv("DATUM_FILE");

	// instantiate connection between each station
	// need to provide a file generated by the ./python/river_sensors.py script
	public static final boolean INSTANTIATE_CONNECTIONS = Boolean.parseBoolean(System.getenv("INSTANTIATE_CONNECTIONS"));
	public static final String CONNECTIONS_FILE = System.getenv("CONNECTIONS_FILE");

	// time series IRI storing list of dates downloaded
	public static final String TIME_IRI = "http://environment.data.gov.uk/flood-monitoring/id/stations/time";
	
	// used in UpdateStations.java, code will download a day's worth of readings to this location
	public static final String READINGS_DIR = System.getProperty("user.home");

	public static final String GEOSERVER_WORKSPACE = System.getenv("GEOSERVER_WORKSPACE");
	public static final String DATABASE = System.getenv("DATABASE");
	public static final String LAYERNAME = System.getenv("LAYERNAME"); // layer name in geoserver, also tablename in postgis
	
	public static final String ONTOP_FILE = System.getenv("ONTOP_FILE");

	public static final String BLAZEGRAPH_NAMESPACE = System.getenv("BLAZEGRAPH_NAMESPACE");

	private EnvConfig() {
		throw new IllegalStateException();
	}
}
