package uk.ac.cam.cares.jps.agent.status.execute;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import uk.ac.cam.cares.jps.agent.status.define.TestDefinition;
import uk.ac.cam.cares.jps.agent.status.record.TestRecord;

/**
 * Abstract base class for all classes that handle executing tests.
 *
 * @author Michael Hillman
 */
public abstract class TestExecutor {

    /**
     * Logger.
     */
    protected final Logger LOGGER = LogManager.getLogger(getClass());

    /**
     * Definition of test to run.
     */
    protected final TestDefinition definition;

    /**
     * Record of completed test.
     */
    protected TestRecord record;

    /**
     * Initialise a new TestExecutor instance with the input test definition.
     *
     * @param definition Definition of test to run.
     */
    public TestExecutor(TestDefinition definition) {
        this.definition = definition;
    }

    /**
     * Returns the test record generated by this execution.
     *
     * @return test record.
     */
    public TestRecord getRecord() {
        return record;
    }

    /**
     * Execute the current test definition.
     */
    public abstract void execute();
}
// End of class.
