#Returns atom's name and number of atoms.
PREFIX ontokin: <https://como.cheng.cam.ac.uk/kb/ontokin/>
PREFIX gc: <http://purl.org/gc/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?atomName ?atomNumber 
WHERE { 
?s ontokin:hasInitialization ?o . 
?o gc:hasMoleculeProperty ?mp . 
?mp gc:hasMolecule ?mol .
?mol gc:hasNumberOfAtoms ?atomNumber.
?mol gc:hasAtom ?atom . 
?atom gc:isElement ?atomName . 
}