#Returns frequencies data, including size, and unit.
PREFIX ontokin: <https://como.cheng.cam.ac.uk/kb/ontokin/>
PREFIX gc: <http://purl.org/gc/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?frequenciesValue ?frequenciesUnit ?frequenciesSize
WHERE { 
?s gc:isCalculationOn ?c . 
?c rdf:type gc:VibrationalAnalysis. 
?c gc:hasResult ?r . 
?r rdf:type gc:Frequency .
?r gc:hasVibrationCount ?frequenciesSize .
?r ontokin:hasFrequenciesValue ?frequenciesValue .
?r gc:hasUnit ?frequenciesUnit. 
}