#Returns atom's coordinates, spin multiplicity value, and atom's name. 
PREFIX ontokin: <https://como.cheng.cam.ac.uk/kb/ontokin/>
PREFIX gc: <http://purl.org/gc/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?atomName ?spinMultiplicityValue  ?coordinateX ?coordinateY ?coordinateZ
WHERE { 
?g09 gc:isCalculationOn ?go. 
?go rdf:type gc:GeometryOptimization .
?go gc:hasMolecule ?m.
?m ontokin:hasSpinMultiplicityValue ?spinMultiplicityValue .
?m gc:hasAtom ?at .
?at gc:isElement ?atomName . 
?at gc:hasAtomCoordinateX ?x . ?x gc:hasValue ?coordinateX.
?at gc:hasAtomCoordinateY ?y . ?y gc:hasValue ?coordinateY.
?at gc:hasAtomCoordinateX ?z . ?z gc:hasValue ?coordinateZ.
}