PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?Measurement ?Name ?Unit
WHERE {
[IRI] <https://www.theworldavatar.com/kg/ontoubemmp/consumesUtilities> ?q .
?q <http://www.ontology-of-units-of-measure.org/resource/om-2/hasValue> ?Measurement .
?Measurement rdfs:label ?Name .
?Measurement <http://www.ontology-of-units-of-measure.org/resource/om-2/hasUnit> ?u .
BIND("Unit" AS ?Unit)
}
