PREFIX ps: <https://www.theworldavatar.com/kg/ps/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?Measurement ?Name ?Unit
WHERE {
[IRI] ps:hasQuantity ?Measurement .
?Measurement rdfs:label ?Name .
?Measurement ps:hasUnit ?Unit
}
